-- Phase 4 seed: the species / variant / class catalog.
--
-- Safe to re-run: every statement carries ON CONFLICT DO NOTHING.
--
-- WHAT THIS FIXES, CONCRETELY:
--   High Elf          -> Elf / High Elf, as a 2024 LINEAGE and a 2014 SUBRACE (both rows)
--   Vulpin            -> Humblefolk / Vulpin (Humblewood). It was never a species.
--   Lotusden Halfling -> Halfling / Lotusden Halfling (Critical Role). Was misfiled as a species.
--   Pallid Elf        -> Elf / Pallid Elf (Critical Role). Same.
--
-- Edition: species_variants.edition is '2014', '2024', or 'both'. The UI defaults to
-- 2024 and offers 2014 on request (decision 6). Elf carries High Elf twice on
-- purpose, once as a lineage and once as a subrace, because the two editions mean
-- genuinely different things by it.

-- Classes -----------------------------------------------------------------
insert into public.classes (system, name, source, partnered, partner, edition, sort)
values
  ('5e', 'Barbarian', 'PHB', false, null, 'both', 1),
  ('5e', 'Bard', 'PHB', false, null, 'both', 2),
  ('5e', 'Cleric', 'PHB', false, null, 'both', 3),
  ('5e', 'Druid', 'PHB', false, null, 'both', 4),
  ('5e', 'Fighter', 'PHB', false, null, 'both', 5),
  ('5e', 'Monk', 'PHB', false, null, 'both', 6),
  ('5e', 'Paladin', 'PHB', false, null, 'both', 7),
  ('5e', 'Ranger', 'PHB', false, null, 'both', 8),
  ('5e', 'Rogue', 'PHB', false, null, 'both', 9),
  ('5e', 'Sorcerer', 'PHB', false, null, 'both', 10),
  ('5e', 'Warlock', 'PHB', false, null, 'both', 11),
  ('5e', 'Wizard', 'PHB', false, null, 'both', 12),
  ('5e', 'Artificer', 'Tasha''s', false, null, 'both', 13),
  ('5e', 'Blood Hunter', 'Critical Role', true, 'Critical Role', 'both', 14)
on conflict (system, name) do nothing;

-- Species -----------------------------------------------------------------
insert into public.species (system, name, source, partnered, partner, edition, sort)
values
  ('5e', 'Human', 'PHB', false, null, 'both', 1),
  ('5e', 'Elf', 'PHB', false, null, 'both', 2),
  ('5e', 'Dwarf', 'PHB', false, null, 'both', 3),
  ('5e', 'Halfling', 'PHB', false, null, 'both', 4),
  ('5e', 'Gnome', 'PHB', false, null, 'both', 5),
  ('5e', 'Dragonborn', 'PHB', false, null, 'both', 6),
  ('5e', 'Tiefling', 'PHB', false, null, 'both', 7),
  ('5e', 'Orc', 'PHB', false, null, 'both', 8),
  ('5e', 'Goliath', 'PHB', false, null, 'both', 9),
  ('5e', 'Aasimar', 'PHB', false, null, 'both', 10),
  ('5e', 'Half-Elf', 'PHB', false, null, '2014', 11),
  ('5e', 'Half-Orc', 'PHB', false, null, '2014', 12),
  ('5e', 'Aarakocra', 'MotM', false, null, 'both', 20),
  ('5e', 'Bugbear', 'MotM', false, null, 'both', 21),
  ('5e', 'Centaur', 'MotM', false, null, 'both', 22),
  ('5e', 'Changeling', 'MotM', false, null, 'both', 23),
  ('5e', 'Deep Gnome', 'MotM', false, null, 'both', 24),
  ('5e', 'Duergar', 'MotM', false, null, 'both', 25),
  ('5e', 'Eladrin', 'MotM', false, null, 'both', 26),
  ('5e', 'Fairy', 'MotM', false, null, 'both', 27),
  ('5e', 'Firbolg', 'MotM', false, null, 'both', 28),
  ('5e', 'Githyanki', 'MotM', false, null, 'both', 29),
  ('5e', 'Githzerai', 'MotM', false, null, 'both', 30),
  ('5e', 'Goblin', 'MotM', false, null, 'both', 31),
  ('5e', 'Harengon', 'MotM', false, null, 'both', 32),
  ('5e', 'Hobgoblin', 'MotM', false, null, 'both', 33),
  ('5e', 'Kenku', 'MotM', false, null, 'both', 34),
  ('5e', 'Kobold', 'MotM', false, null, 'both', 35),
  ('5e', 'Lizardfolk', 'MotM', false, null, 'both', 36),
  ('5e', 'Minotaur', 'MotM', false, null, 'both', 37),
  ('5e', 'Satyr', 'MotM', false, null, 'both', 38),
  ('5e', 'Sea Elf', 'MotM', false, null, 'both', 39),
  ('5e', 'Shadar-kai', 'MotM', false, null, 'both', 40),
  ('5e', 'Tabaxi', 'MotM', false, null, 'both', 41),
  ('5e', 'Tortle', 'MotM', false, null, 'both', 42),
  ('5e', 'Triton', 'MotM', false, null, 'both', 43),
  ('5e', 'Yuan-ti', 'MotM', false, null, 'both', 44),
  ('5e', 'Shifter', 'MotM', false, null, 'both', 45),
  ('5e', 'Genasi', 'MotM', false, null, 'both', 46),
  ('5e', 'Warforged', 'Eberron', false, null, 'both', 50),
  ('5e', 'Kalashtar', 'Eberron', false, null, 'both', 51),
  ('5e', 'Dhampir', 'Van Richten''s', false, null, 'both', 55),
  ('5e', 'Hexblood', 'Van Richten''s', false, null, 'both', 56),
  ('5e', 'Reborn', 'Van Richten''s', false, null, 'both', 57),
  ('5e', 'Astral Elf', 'Spelljammer', false, null, 'both', 60),
  ('5e', 'Autognome', 'Spelljammer', false, null, 'both', 61),
  ('5e', 'Giff', 'Spelljammer', false, null, 'both', 62),
  ('5e', 'Hadozee', 'Spelljammer', false, null, 'both', 63),
  ('5e', 'Plasmoid', 'Spelljammer', false, null, 'both', 64),
  ('5e', 'Thri-kreen', 'Spelljammer', false, null, 'both', 65),
  ('5e', 'Owlin', 'Strixhaven', false, null, 'both', 70),
  ('5e', 'Leonin', 'Theros', false, null, 'both', 71),
  ('5e', 'Loxodon', 'Ravnica', false, null, 'both', 72),
  ('5e', 'Simic Hybrid', 'Ravnica', false, null, 'both', 73),
  ('5e', 'Vedalken', 'Ravnica', false, null, 'both', 74),
  ('5e', 'Verdan', 'Acquisitions Inc.', false, null, 'both', 75),
  ('5e', 'Grung', 'One Grung Above', false, null, 'both', 76),
  ('5e', 'Locathah', 'Locathah Rising', false, null, 'both', 77),
  ('5e', 'Birdfolk', 'Humblewood', true, 'Humblewood', 'both', 80),
  ('5e', 'Humblefolk', 'Humblewood', true, 'Humblewood', 'both', 81),
  ('5e', 'Aarakocra (Tal''Dorei)', 'Tal''Dorei', true, 'Critical Role', 'both', 85)
on conflict (system, name) do nothing;

-- Species variants: the dimension that did not exist ----------------------
insert into public.species_variants (species_id, name, variant_kind, source, partnered, partner, edition, sort)
values
  ((select id from public.species where system='5e' and name='Human'), 'Standard', 'subrace', 'PHB', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Human'), 'Variant', 'subrace', 'PHB', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Elf'), 'Drow', 'lineage', 'PHB', false, null, '2024', 1),
  ((select id from public.species where system='5e' and name='Elf'), 'High Elf', 'lineage', 'PHB', false, null, '2024', 2),
  ((select id from public.species where system='5e' and name='Elf'), 'Wood Elf', 'lineage', 'PHB', false, null, '2024', 3),
  ((select id from public.species where system='5e' and name='Elf'), 'High Elf', 'subrace', 'PHB', false, null, '2014', 4),
  ((select id from public.species where system='5e' and name='Elf'), 'Wood Elf', 'subrace', 'PHB', false, null, '2014', 5),
  ((select id from public.species where system='5e' and name='Elf'), 'Dark Elf (Drow)', 'subrace', 'PHB', false, null, '2014', 6),
  ((select id from public.species where system='5e' and name='Elf'), 'Eladrin', 'subrace', 'MotM', false, null, '2014', 7),
  ((select id from public.species where system='5e' and name='Elf'), 'Sea Elf', 'subrace', 'MotM', false, null, '2014', 8),
  ((select id from public.species where system='5e' and name='Elf'), 'Shadar-kai', 'subrace', 'MotM', false, null, '2014', 9),
  ((select id from public.species where system='5e' and name='Elf'), 'Pallid Elf', 'subrace', 'Explorer''s Guide to Wildemount', true, 'Critical Role', '2014', 10),
  ((select id from public.species where system='5e' and name='Dwarf'), 'Hill Dwarf', 'subrace', 'PHB', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Dwarf'), 'Mountain Dwarf', 'subrace', 'PHB', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Dwarf'), 'Duergar', 'subrace', 'MotM', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Halfling'), 'Lightfoot', 'subrace', 'PHB', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Halfling'), 'Stout', 'subrace', 'PHB', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Halfling'), 'Ghostwise', 'subrace', 'SCAG', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Halfling'), 'Lotusden Halfling', 'subrace', 'Explorer''s Guide to Wildemount', true, 'Critical Role', '2014', 4),
  ((select id from public.species where system='5e' and name='Gnome'), 'Forest Gnome', 'subrace', 'PHB', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Gnome'), 'Rock Gnome', 'subrace', 'PHB', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Gnome'), 'Deep Gnome', 'subrace', 'MotM', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Black Dragonborn', 'lineage', 'PHB', false, null, '2024', 1),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Blue Dragonborn', 'lineage', 'PHB', false, null, '2024', 2),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Brass Dragonborn', 'lineage', 'PHB', false, null, '2024', 3),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Bronze Dragonborn', 'lineage', 'PHB', false, null, '2024', 4),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Copper Dragonborn', 'lineage', 'PHB', false, null, '2024', 5),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Gold Dragonborn', 'lineage', 'PHB', false, null, '2024', 6),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Green Dragonborn', 'lineage', 'PHB', false, null, '2024', 7),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Red Dragonborn', 'lineage', 'PHB', false, null, '2024', 8),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Silver Dragonborn', 'lineage', 'PHB', false, null, '2024', 9),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'White Dragonborn', 'lineage', 'PHB', false, null, '2024', 10),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Chromatic', 'subrace', 'Fizban''s', false, null, '2014', 11),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Metallic', 'subrace', 'Fizban''s', false, null, '2014', 12),
  ((select id from public.species where system='5e' and name='Dragonborn'), 'Gem', 'subrace', 'Fizban''s', false, null, '2014', 13),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Abyssal', 'lineage', 'PHB', false, null, '2024', 1),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Chthonic', 'lineage', 'PHB', false, null, '2024', 2),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Infernal', 'lineage', 'PHB', false, null, '2024', 3),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Asmodeus', 'subrace', 'MToF', false, null, '2014', 4),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Baalzebul', 'subrace', 'MToF', false, null, '2014', 5),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Dispater', 'subrace', 'MToF', false, null, '2014', 6),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Fierna', 'subrace', 'MToF', false, null, '2014', 7),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Glasya', 'subrace', 'MToF', false, null, '2014', 8),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Levistus', 'subrace', 'MToF', false, null, '2014', 9),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Mammon', 'subrace', 'MToF', false, null, '2014', 10),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Mephistopheles', 'subrace', 'MToF', false, null, '2014', 11),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Zariel', 'subrace', 'MToF', false, null, '2014', 12),
  ((select id from public.species where system='5e' and name='Tiefling'), 'Feral', 'subrace', 'SCAG', false, null, '2014', 13),
  ((select id from public.species where system='5e' and name='Goliath'), 'Cloud Giant', 'lineage', 'PHB', false, null, '2024', 1),
  ((select id from public.species where system='5e' and name='Goliath'), 'Fire Giant', 'lineage', 'PHB', false, null, '2024', 2),
  ((select id from public.species where system='5e' and name='Goliath'), 'Frost Giant', 'lineage', 'PHB', false, null, '2024', 3),
  ((select id from public.species where system='5e' and name='Goliath'), 'Hill Giant', 'lineage', 'PHB', false, null, '2024', 4),
  ((select id from public.species where system='5e' and name='Goliath'), 'Stone Giant', 'lineage', 'PHB', false, null, '2024', 5),
  ((select id from public.species where system='5e' and name='Goliath'), 'Storm Giant', 'lineage', 'PHB', false, null, '2024', 6),
  ((select id from public.species where system='5e' and name='Aasimar'), 'Protector', 'subrace', 'VGtM', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Aasimar'), 'Scourge', 'subrace', 'VGtM', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Aasimar'), 'Fallen', 'subrace', 'VGtM', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Shifter'), 'Beasthide', 'subrace', 'MotM', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Shifter'), 'Longtooth', 'subrace', 'MotM', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Shifter'), 'Swiftstride', 'subrace', 'MotM', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Shifter'), 'Wildhunt', 'subrace', 'MotM', false, null, '2014', 4),
  ((select id from public.species where system='5e' and name='Genasi'), 'Air Genasi', 'subrace', 'MotM', false, null, '2014', 1),
  ((select id from public.species where system='5e' and name='Genasi'), 'Earth Genasi', 'subrace', 'MotM', false, null, '2014', 2),
  ((select id from public.species where system='5e' and name='Genasi'), 'Fire Genasi', 'subrace', 'MotM', false, null, '2014', 3),
  ((select id from public.species where system='5e' and name='Genasi'), 'Water Genasi', 'subrace', 'MotM', false, null, '2014', 4),
  ((select id from public.species where system='5e' and name='Birdfolk'), 'Corvum', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 1),
  ((select id from public.species where system='5e' and name='Birdfolk'), 'Gallus', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 2),
  ((select id from public.species where system='5e' and name='Birdfolk'), 'Luma', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 3),
  ((select id from public.species where system='5e' and name='Birdfolk'), 'Raptor', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 4),
  ((select id from public.species where system='5e' and name='Birdfolk'), 'Strig', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 5),
  ((select id from public.species where system='5e' and name='Humblefolk'), 'Cervan', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 1),
  ((select id from public.species where system='5e' and name='Humblefolk'), 'Hedge', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 2),
  ((select id from public.species where system='5e' and name='Humblefolk'), 'Jerbeen', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 3),
  ((select id from public.species where system='5e' and name='Humblefolk'), 'Mapach', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 4),
  ((select id from public.species where system='5e' and name='Humblefolk'), 'Vulpin', 'subrace', 'Humblewood', true, 'Humblewood', 'both', 5)
on conflict (species_id, name, variant_kind) do nothing;
