// Daggerheart domain card catalog (SRD 1.0 Domain Card Reference). MECHANICS ONLY: each card's name,
// domain, level, recall cost, and type. Darrington Press's card EFFECT TEXT is deliberately NOT shipped
// (open under the Darrington Press Community Gaming License, but this build stores only the functional
// index, like a spell list, so players pick and track cards while reading effects from their own SRD).
// Generated from the SRD appendix; 188 cards across the nine domains.

import type { DHDomainId } from "./character";

export type DHCardType = "Ability" | "Spell" | "Grimoire";

export interface DHDomainCard {
  id: string;
  name: string;
  domain: DHDomainId;
  level: number;      // 1-10; a character can take a card at or below their level
  recall: number;     // Recall Cost (Stress to swap it out of the loadout)
  type: DHCardType;
}

export const DH_DOMAIN_CARDS: DHDomainCard[] = [
  { id: "arcana-rune-ward", name: "Rune Ward", domain: "arcana", level: 1, recall: 0, type: "Spell" },
  { id: "arcana-unleash-chaos", name: "Unleash Chaos", domain: "arcana", level: 1, recall: 1, type: "Spell" },
  { id: "arcana-wall-walk", name: "Wall Walk", domain: "arcana", level: 1, recall: 1, type: "Spell" },
  { id: "arcana-cinder-grasp", name: "Cinder Grasp", domain: "arcana", level: 2, recall: 1, type: "Spell" },
  { id: "arcana-floating-eye", name: "Floating Eye", domain: "arcana", level: 2, recall: 0, type: "Spell" },
  { id: "arcana-counterspell", name: "Counterspell", domain: "arcana", level: 3, recall: 2, type: "Spell" },
  { id: "arcana-flight", name: "Flight", domain: "arcana", level: 3, recall: 1, type: "Spell" },
  { id: "arcana-blink-out", name: "Blink Out", domain: "arcana", level: 4, recall: 1, type: "Spell" },
  { id: "arcana-preservation-blast", name: "Preservation Blast", domain: "arcana", level: 4, recall: 2, type: "Spell" },
  { id: "arcana-chain-lightning", name: "Chain Lightning", domain: "arcana", level: 5, recall: 1, type: "Spell" },
  { id: "arcana-premonition", name: "Premonition", domain: "arcana", level: 5, recall: 2, type: "Spell" },
  { id: "arcana-rift-walker", name: "Rift Walker", domain: "arcana", level: 6, recall: 2, type: "Spell" },
  { id: "arcana-telekinesis", name: "Telekinesis", domain: "arcana", level: 6, recall: 0, type: "Spell" },
  { id: "arcana-arcana-touched", name: "Arcana-Touched", domain: "arcana", level: 7, recall: 2, type: "Ability" },
  { id: "arcana-cloaking-blast", name: "Cloaking Blast", domain: "arcana", level: 7, recall: 2, type: "Spell" },
  { id: "arcana-arcane-reflection", name: "Arcane Reflection", domain: "arcana", level: 8, recall: 1, type: "Spell" },
  { id: "arcana-confusing-aura", name: "Confusing Aura", domain: "arcana", level: 8, recall: 2, type: "Spell" },
  { id: "arcana-earthquake", name: "Earthquake", domain: "arcana", level: 9, recall: 2, type: "Spell" },
  { id: "arcana-sensory-projection", name: "Sensory Projection", domain: "arcana", level: 9, recall: 0, type: "Spell" },
  { id: "arcana-adjust-reality", name: "Adjust Reality", domain: "arcana", level: 10, recall: 1, type: "Spell" },
  { id: "arcana-falling-sky", name: "Falling Sky", domain: "arcana", level: 10, recall: 1, type: "Spell" },
  { id: "blade-get-back-up", name: "Get Back Up", domain: "blade", level: 1, recall: 1, type: "Ability" },
  { id: "blade-not-good-enough", name: "Not Good Enough", domain: "blade", level: 1, recall: 1, type: "Ability" },
  { id: "blade-whirlwind", name: "Whirlwind", domain: "blade", level: 1, recall: 0, type: "Ability" },
  { id: "blade-a-soldier-s-bond", name: "A Soldier\u2019s Bond", domain: "blade", level: 2, recall: 1, type: "Ability" },
  { id: "blade-reckless", name: "Reckless", domain: "blade", level: 2, recall: 1, type: "Ability" },
  { id: "blade-scramble", name: "Scramble", domain: "blade", level: 3, recall: 1, type: "Ability" },
  { id: "blade-versatile-fighter", name: "Versatile Fighter", domain: "blade", level: 3, recall: 1, type: "Ability" },
  { id: "blade-deadly-focus", name: "Deadly Focus", domain: "blade", level: 4, recall: 2, type: "Ability" },
  { id: "blade-fortified-armor", name: "Fortified Armor", domain: "blade", level: 4, recall: 0, type: "Ability" },
  { id: "blade-champion-s-edge", name: "Champion\u2019s Edge", domain: "blade", level: 5, recall: 1, type: "Ability" },
  { id: "blade-vitality", name: "Vitality", domain: "blade", level: 5, recall: 0, type: "Ability" },
  { id: "blade-battle-hardened", name: "Battle-Hardened", domain: "blade", level: 6, recall: 2, type: "Ability" },
  { id: "blade-rage-up", name: "Rage Up", domain: "blade", level: 6, recall: 1, type: "Ability" },
  { id: "blade-blade-touched", name: "Blade-Touched", domain: "blade", level: 7, recall: 1, type: "Ability" },
  { id: "blade-glancing-blow", name: "Glancing Blow", domain: "blade", level: 7, recall: 1, type: "Ability" },
  { id: "blade-battle-cry", name: "Battle Cry", domain: "blade", level: 8, recall: 2, type: "Ability" },
  { id: "blade-frenzy", name: "Frenzy", domain: "blade", level: 8, recall: 3, type: "Ability" },
  { id: "blade-gore-and-glory", name: "Gore and Glory", domain: "blade", level: 9, recall: 2, type: "Ability" },
  { id: "blade-reaper-s-strike", name: "Reaper\u2019s Strike", domain: "blade", level: 9, recall: 3, type: "Ability" },
  { id: "blade-battle-monster", name: "Battle Monster", domain: "blade", level: 10, recall: 0, type: "Ability" },
  { id: "blade-onslaught", name: "Onslaught", domain: "blade", level: 10, recall: 3, type: "Ability" },
  { id: "bone-deft-maneuvers", name: "Deft Maneuvers", domain: "bone", level: 1, recall: 0, type: "Ability" },
  { id: "bone-i-see-it-coming", name: "I See It Coming", domain: "bone", level: 1, recall: 1, type: "Ability" },
  { id: "bone-untouchable", name: "Untouchable", domain: "bone", level: 1, recall: 1, type: "Ability" },
  { id: "bone-ferocity", name: "Ferocity", domain: "bone", level: 2, recall: 2, type: "Ability" },
  { id: "bone-strategic-approach", name: "Strategic Approach", domain: "bone", level: 2, recall: 1, type: "Ability" },
  { id: "bone-brace", name: "Brace", domain: "bone", level: 3, recall: 1, type: "Ability" },
  { id: "bone-tactician", name: "Tactician", domain: "bone", level: 3, recall: 1, type: "Ability" },
  { id: "bone-boost", name: "Boost", domain: "bone", level: 4, recall: 1, type: "Ability" },
  { id: "bone-redirect", name: "Redirect", domain: "bone", level: 4, recall: 1, type: "Ability" },
  { id: "bone-know-thy-enemy", name: "Know Thy Enemy", domain: "bone", level: 5, recall: 1, type: "Ability" },
  { id: "bone-signature-move", name: "Signature Move", domain: "bone", level: 5, recall: 1, type: "Ability" },
  { id: "bone-rapid-riposte", name: "Rapid Riposte", domain: "bone", level: 6, recall: 0, type: "Ability" },
  { id: "bone-recovery", name: "Recovery", domain: "bone", level: 6, recall: 1, type: "Ability" },
  { id: "bone-bone-touched", name: "Bone-Touched", domain: "bone", level: 7, recall: 2, type: "Ability" },
  { id: "bone-cruel-precision", name: "Cruel Precision", domain: "bone", level: 7, recall: 1, type: "Ability" },
  { id: "bone-breaking-blow", name: "Breaking Blow", domain: "bone", level: 8, recall: 3, type: "Ability" },
  { id: "bone-wrangle", name: "Wrangle", domain: "bone", level: 8, recall: 1, type: "Ability" },
  { id: "bone-on-the-brink", name: "On the Brink", domain: "bone", level: 9, recall: 1, type: "Ability" },
  { id: "bone-splintering-strike", name: "Splintering Strike", domain: "bone", level: 9, recall: 3, type: "Ability" },
  { id: "bone-deathrun", name: "Deathrun", domain: "bone", level: 10, recall: 1, type: "Ability" },
  { id: "bone-swift-step", name: "Swift Step", domain: "bone", level: 10, recall: 2, type: "Ability" },
  { id: "codex-book-of-ava", name: "Book of Ava", domain: "codex", level: 1, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-illiat", name: "Book of Illiat", domain: "codex", level: 1, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-tyfar", name: "Book of Tyfar", domain: "codex", level: 1, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-sitil", name: "Book of Sitil", domain: "codex", level: 2, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-vagras", name: "Book of Vagras", domain: "codex", level: 2, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-korvax", name: "Book of Korvax", domain: "codex", level: 3, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-norai", name: "Book of Norai", domain: "codex", level: 3, recall: 2, type: "Grimoire" },
  { id: "codex-book-of-exota", name: "Book of Exota", domain: "codex", level: 4, recall: 3, type: "Grimoire" },
  { id: "codex-book-of-grynn", name: "Book of Grynn", domain: "codex", level: 4, recall: 2, type: "Grimoire" },
  { id: "codex-manifest-wall", name: "Manifest Wall", domain: "codex", level: 5, recall: 2, type: "Spell" },
  { id: "codex-teleport", name: "Teleport", domain: "codex", level: 5, recall: 2, type: "Spell" },
  { id: "codex-banish", name: "Banish", domain: "codex", level: 6, recall: 0, type: "Spell" },
  { id: "codex-sigil-of-retribution", name: "Sigil of Retribution", domain: "codex", level: 6, recall: 2, type: "Spell" },
  { id: "codex-codex-touched", name: "Codex-Touched", domain: "codex", level: 7, recall: 2, type: "Ability" },
  { id: "codex-book-of-vyola", name: "Book of Vyola", domain: "codex", level: 8, recall: 2, type: "Grimoire" },
  { id: "codex-safe-haven", name: "Safe Haven", domain: "codex", level: 8, recall: 3, type: "Spell" },
  { id: "codex-book-of-ronin", name: "Book of Ronin", domain: "codex", level: 9, recall: 4, type: "Grimoire" },
  { id: "codex-disintegration-wave", name: "Disintegration Wave", domain: "codex", level: 9, recall: 4, type: "Spell" },
  { id: "codex-book-of-yarrow", name: "Book of Yarrow", domain: "codex", level: 10, recall: 2, type: "Grimoire" },
  { id: "codex-transcendent-union", name: "Transcendent Union", domain: "codex", level: 10, recall: 1, type: "Spell" },
  { id: "grace-deft-deceiver", name: "Deft Deceiver", domain: "grace", level: 1, recall: 0, type: "Ability" },
  { id: "grace-enrapture", name: "Enrapture", domain: "grace", level: 1, recall: 0, type: "Spell" },
  { id: "grace-inspirational-words", name: "Inspirational Words", domain: "grace", level: 1, recall: 1, type: "Ability" },
  { id: "grace-tell-no-lies", name: "Tell No Lies", domain: "grace", level: 2, recall: 1, type: "Spell" },
  { id: "grace-troublemaker", name: "Troublemaker", domain: "grace", level: 2, recall: 2, type: "Ability" },
  { id: "grace-hypnotic-shimmer", name: "Hypnotic Shimmer", domain: "grace", level: 3, recall: 1, type: "Spell" },
  { id: "grace-invisibility", name: "Invisibility", domain: "grace", level: 3, recall: 1, type: "Spell" },
  { id: "grace-soothing-speech", name: "Soothing Speech", domain: "grace", level: 4, recall: 1, type: "Ability" },
  { id: "grace-through-your-eyes", name: "Through Your Eyes", domain: "grace", level: 4, recall: 1, type: "Spell" },
  { id: "grace-thought-delver", name: "Thought Delver", domain: "grace", level: 5, recall: 2, type: "Spell" },
  { id: "grace-words-of-discord", name: "Words of Discord", domain: "grace", level: 5, recall: 1, type: "Spell" },
  { id: "grace-never-upstaged", name: "Never Upstaged", domain: "grace", level: 6, recall: 2, type: "Ability" },
  { id: "grace-share-the-burden", name: "Share the Burden", domain: "grace", level: 6, recall: 0, type: "Spell" },
  { id: "grace-endless-charisma", name: "Endless Charisma", domain: "grace", level: 7, recall: 1, type: "Ability" },
  { id: "grace-grace-touched", name: "Grace-Touched", domain: "grace", level: 7, recall: 2, type: "Ability" },
  { id: "grace-astral-projection", name: "Astral Projection", domain: "grace", level: 8, recall: 0, type: "Spell" },
  { id: "grace-mass-enrapture", name: "Mass Enrapture", domain: "grace", level: 8, recall: 3, type: "Spell" },
  { id: "grace-copycat", name: "Copycat", domain: "grace", level: 9, recall: 3, type: "Spell" },
  { id: "grace-master-of-the-craft", name: "Master of the Craft", domain: "grace", level: 9, recall: 0, type: "Ability" },
  { id: "grace-encore", name: "Encore", domain: "grace", level: 10, recall: 1, type: "Spell" },
  { id: "grace-notorious", name: "Notorious", domain: "grace", level: 10, recall: 0, type: "Ability" },
  { id: "midnight-pick-and-pull", name: "Pick and Pull", domain: "midnight", level: 1, recall: 0, type: "Ability" },
  { id: "midnight-rain-of-blades", name: "Rain of Blades", domain: "midnight", level: 1, recall: 1, type: "Spell" },
  { id: "midnight-uncanny-disguise", name: "Uncanny Disguise", domain: "midnight", level: 1, recall: 0, type: "Spell" },
  { id: "midnight-midnight-spirit", name: "Midnight Spirit", domain: "midnight", level: 2, recall: 1, type: "Spell" },
  { id: "midnight-shadowbind", name: "Shadowbind", domain: "midnight", level: 2, recall: 0, type: "Spell" },
  { id: "midnight-chokehold", name: "Chokehold", domain: "midnight", level: 3, recall: 1, type: "Ability" },
  { id: "midnight-veil-of-night", name: "Veil of Night", domain: "midnight", level: 3, recall: 1, type: "Spell" },
  { id: "midnight-glyph-of-nightfall", name: "Glyph of Nightfall", domain: "midnight", level: 4, recall: 1, type: "Spell" },
  { id: "midnight-stealth-expertise", name: "Stealth Expertise", domain: "midnight", level: 4, recall: 0, type: "Ability" },
  { id: "midnight-hush", name: "Hush", domain: "midnight", level: 5, recall: 1, type: "Spell" },
  { id: "midnight-phantom-retreat", name: "Phantom Retreat", domain: "midnight", level: 5, recall: 2, type: "Spell" },
  { id: "midnight-dark-whispers", name: "Dark Whispers", domain: "midnight", level: 6, recall: 0, type: "Spell" },
  { id: "midnight-mass-disguise", name: "Mass Disguise", domain: "midnight", level: 6, recall: 0, type: "Spell" },
  { id: "midnight-midnight-touched", name: "Midnight-Touched", domain: "midnight", level: 7, recall: 2, type: "Ability" },
  { id: "midnight-vanishing-dodge", name: "Vanishing Dodge", domain: "midnight", level: 7, recall: 1, type: "Spell" },
  { id: "midnight-shadowhunter", name: "Shadowhunter", domain: "midnight", level: 8, recall: 2, type: "Ability" },
  { id: "midnight-spellcharge", name: "Spellcharge", domain: "midnight", level: 8, recall: 1, type: "Spell" },
  { id: "midnight-night-terror", name: "Night Terror", domain: "midnight", level: 9, recall: 2, type: "Spell" },
  { id: "midnight-twilight-toll", name: "Twilight Toll", domain: "midnight", level: 9, recall: 1, type: "Ability" },
  { id: "midnight-eclipse", name: "Eclipse", domain: "midnight", level: 10, recall: 2, type: "Spell" },
  { id: "midnight-specter-of-the-dark", name: "Specter of the Dark", domain: "midnight", level: 10, recall: 1, type: "Spell" },
  { id: "sage-gifted-tracker", name: "Gifted Tracker", domain: "sage", level: 1, recall: 0, type: "Ability" },
  { id: "sage-nature-s-tongue", name: "Nature\u2019s Tongue", domain: "sage", level: 1, recall: 0, type: "Ability" },
  { id: "sage-vicious-entangle", name: "Vicious Entangle", domain: "sage", level: 1, recall: 1, type: "Spell" },
  { id: "sage-conjure-swarm", name: "Conjure Swarm", domain: "sage", level: 2, recall: 1, type: "Spell" },
  { id: "sage-natural-familiar", name: "Natural Familiar", domain: "sage", level: 2, recall: 1, type: "Spell" },
  { id: "sage-corrosive-projectile", name: "Corrosive Projectile", domain: "sage", level: 3, recall: 1, type: "Spell" },
  { id: "sage-towering-stalk", name: "Towering Stalk", domain: "sage", level: 3, recall: 1, type: "Spell" },
  { id: "sage-death-grip", name: "Death Grip", domain: "sage", level: 4, recall: 1, type: "Spell" },
  { id: "sage-healing-field", name: "Healing Field", domain: "sage", level: 4, recall: 2, type: "Spell" },
  { id: "sage-thorn-skin", name: "Thorn Skin", domain: "sage", level: 5, recall: 1, type: "Spell" },
  { id: "sage-wild-fortress", name: "Wild Fortress", domain: "sage", level: 5, recall: 1, type: "Spell" },
  { id: "sage-conjured-steeds", name: "Conjured Steeds", domain: "sage", level: 6, recall: 0, type: "Spell" },
  { id: "sage-forager", name: "Forager", domain: "sage", level: 6, recall: 1, type: "Ability" },
  { id: "sage-sage-touched", name: "Sage-Touched", domain: "sage", level: 7, recall: 2, type: "Ability" },
  { id: "sage-wild-surge", name: "Wild Surge", domain: "sage", level: 7, recall: 2, type: "Spell" },
  { id: "sage-forest-sprites", name: "Forest Sprites", domain: "sage", level: 8, recall: 2, type: "Spell" },
  { id: "sage-rejuvenation-barrier", name: "Rejuvenation Barrier", domain: "sage", level: 8, recall: 1, type: "Spell" },
  { id: "sage-fane-of-the-wilds", name: "Fane of the Wilds", domain: "sage", level: 9, recall: 2, type: "Ability" },
  { id: "sage-plant-dominion", name: "Plant Dominion", domain: "sage", level: 9, recall: 1, type: "Spell" },
  { id: "sage-force-of-nature", name: "Force of Nature", domain: "sage", level: 10, recall: 2, type: "Spell" },
  { id: "sage-tempest", name: "Tempest", domain: "sage", level: 10, recall: 2, type: "Spell" },
  { id: "splendor-bolt-beacon", name: "Bolt Beacon", domain: "splendor", level: 1, recall: 1, type: "Spell" },
  { id: "splendor-mending-touch", name: "Mending Touch", domain: "splendor", level: 1, recall: 1, type: "Spell" },
  { id: "splendor-reassurance", name: "Reassurance", domain: "splendor", level: 1, recall: 0, type: "Ability" },
  { id: "splendor-final-words", name: "Final Words", domain: "splendor", level: 2, recall: 1, type: "Spell" },
  { id: "splendor-healing-hands", name: "Healing Hands", domain: "splendor", level: 2, recall: 1, type: "Spell" },
  { id: "splendor-second-wind", name: "Second Wind", domain: "splendor", level: 3, recall: 2, type: "Ability" },
  { id: "splendor-voice-of-reason", name: "Voice of Reason", domain: "splendor", level: 3, recall: 1, type: "Ability" },
  { id: "splendor-divination", name: "Divination", domain: "splendor", level: 4, recall: 1, type: "Spell" },
  { id: "splendor-life-ward", name: "Life Ward", domain: "splendor", level: 4, recall: 1, type: "Spell" },
  { id: "splendor-shape-material", name: "Shape Material", domain: "splendor", level: 5, recall: 1, type: "Spell" },
  { id: "splendor-smite", name: "Smite", domain: "splendor", level: 5, recall: 2, type: "Spell" },
  { id: "splendor-restoration", name: "Restoration", domain: "splendor", level: 6, recall: 2, type: "Spell" },
  { id: "splendor-zone-of-protection", name: "Zone of Protection", domain: "splendor", level: 6, recall: 2, type: "Spell" },
  { id: "splendor-healing-strike", name: "Healing Strike", domain: "splendor", level: 7, recall: 1, type: "Spell" },
  { id: "splendor-splendor-touched", name: "Splendor-Touched", domain: "splendor", level: 7, recall: 2, type: "Ability" },
  { id: "splendor-shield-aura", name: "Shield Aura", domain: "splendor", level: 8, recall: 2, type: "Spell" },
  { id: "splendor-stunning-sunlight", name: "Stunning Sunlight", domain: "splendor", level: 8, recall: 2, type: "Spell" },
  { id: "splendor-overwhelming-aura", name: "Overwhelming Aura", domain: "splendor", level: 9, recall: 2, type: "Spell" },
  { id: "splendor-salvation-beam", name: "Salvation Beam", domain: "splendor", level: 9, recall: 2, type: "Spell" },
  { id: "splendor-invigoration", name: "Invigoration", domain: "splendor", level: 10, recall: 3, type: "Spell" },
  { id: "splendor-resurrection", name: "Resurrection", domain: "splendor", level: 10, recall: 2, type: "Spell" },
  { id: "valor-bare-bones", name: "Bare Bones", domain: "valor", level: 1, recall: 0, type: "Ability" },
  { id: "valor-forceful-push", name: "Forceful Push", domain: "valor", level: 1, recall: 0, type: "Ability" },
  { id: "valor-i-am-your-shield", name: "I Am Your Shield", domain: "valor", level: 1, recall: 1, type: "Ability" },
  { id: "valor-body-basher", name: "Body Basher", domain: "valor", level: 2, recall: 1, type: "Ability" },
  { id: "valor-bold-presence", name: "Bold Presence", domain: "valor", level: 2, recall: 0, type: "Ability" },
  { id: "valor-critical-inspiration", name: "Critical Inspiration", domain: "valor", level: 3, recall: 1, type: "Ability" },
  { id: "valor-lean-on-me", name: "Lean on Me", domain: "valor", level: 3, recall: 1, type: "Ability" },
  { id: "valor-goad-them-on", name: "Goad Them on", domain: "valor", level: 4, recall: 1, type: "Ability" },
  { id: "valor-support-tank", name: "Support Tank", domain: "valor", level: 4, recall: 2, type: "Ability" },
  { id: "valor-armorer", name: "Armorer", domain: "valor", level: 5, recall: 1, type: "Ability" },
  { id: "valor-rousing-strike", name: "Rousing Strike", domain: "valor", level: 5, recall: 1, type: "Ability" },
  { id: "valor-inevitable", name: "Inevitable", domain: "valor", level: 6, recall: 1, type: "Ability" },
  { id: "valor-rise-up", name: "Rise Up", domain: "valor", level: 6, recall: 2, type: "Ability" },
  { id: "valor-shrug-it-off", name: "Shrug It Off", domain: "valor", level: 7, recall: 1, type: "Ability" },
  { id: "valor-valor-touched", name: "Valor-Touched", domain: "valor", level: 7, recall: 1, type: "Ability" },
  { id: "valor-full-surge", name: "Full Surge", domain: "valor", level: 8, recall: 1, type: "Ability" },
  { id: "valor-ground-pound", name: "Ground Pound", domain: "valor", level: 8, recall: 2, type: "Ability" },
  { id: "valor-hold-the-line", name: "Hold the Line", domain: "valor", level: 9, recall: 1, type: "Ability" },
  { id: "valor-lead-by-example", name: "Lead By Example", domain: "valor", level: 9, recall: 3, type: "Ability" },
  { id: "valor-unbreakable", name: "Unbreakable", domain: "valor", level: 10, recall: 4, type: "Ability" },
  { id: "valor-unyielding-armor", name: "Unyielding Armor", domain: "valor", level: 10, recall: 1, type: "Ability" },
];

// Cards a character may choose: those belonging to either of the class's two domains, at or below the
// character's level. Sorted by level then name for a stable picker.
export function cardsForDomains(domains: readonly string[], maxLevel: number): DHDomainCard[] {
  const set = new Set(domains);
  return DH_DOMAIN_CARDS
    .filter((c) => set.has(c.domain) && c.level <= maxLevel)
    .sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));
}

export function cardById(id: string): DHDomainCard | undefined {
  return DH_DOMAIN_CARDS.find((c) => c.id === id);
}
