// Lancer weapon and system data (from the public lancer-data / COMP-CON data set, used under the Lancer
// Third Party License). MECHANICS ONLY: each item's stats, tags, and SP cost. No Massif Press descriptive
// prose (weapon/system effect text or fiction) ships here. Tag labels are the game's short mechanical
// keywords with their values substituted in. Ship-class weapons are omitted (not mech-mountable). See
// lib/systems/lancer.ts for the required in-app attribution.

import type { LancerWeapon, LancerSystem, LancerMod } from "./loadout";

export const LANCER_WEAPONS: LancerWeapon[] = [
  { id: "mw_fuel_rod_gun", name: "Fuel Rod Gun", size: "Main", type: "CQB", damage: ["1d3+2 Energy"], range: ["Range 3", "Threat 3"], tags: ["Limited 3", "Unique"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "mw_lancaster_integrated", name: "Latch Drone", size: "Main", type: "Launcher", damage: [], range: ["Range 8"], tags: [], manufacturer: "", license: "", licenseLevel: 0 },
  { id: "mw_raleigh_integrated", name: "M35 Mjolnir", size: "Main", type: "CQB", damage: ["4 Kinetic"], range: ["Range 5", "Threat 3"], tags: [], manufacturer: "", license: "", licenseLevel: 0 },
  { id: "mw_prototype_1", name: "Prototype Weapon I", size: "Main", type: "Special", damage: ["1d6+2 Variable"], range: ["Threat 1", "Range 10"], tags: ["Limited 1d6+2", "Overkill ", "Set Max Uses", "Set Damage Type"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "mw_prototype_2", name: "Prototype Weapon II", size: "Main", type: "Special", damage: ["1d6+2 Variable"], range: ["Threat 1", "Range 10"], tags: ["Limited 1d6+2", "Overkill ", "Set Max Uses", "Set Damage Type"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "mw_prototype_3", name: "Prototype Weapon III", size: "Main", type: "Special", damage: ["1d6+4 Variable"], range: ["Threat 1", "Range 10"], tags: ["Limited 2d6", "Overkill ", "Set Max Uses", "Set Damage Type"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "mw_sherman_integrated", name: "ZF4 SOLIDCORE", size: "Main", type: "Cannon", damage: [], range: [], tags: ["Ordnance"], manufacturer: "", license: "", licenseLevel: 0 },
  { id: "mw_missile_rack", name: "Missile Rack", size: "Auxiliary", type: "Launcher", damage: ["1d3+1 Explosive"], range: ["Range 10", "Blast 1"], tags: ["Loading"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_nexus_light", name: "Nexus (Light)", size: "Auxiliary", type: "Nexus", damage: ["1d3 Kinetic"], range: ["Range 10"], tags: ["Smart"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_pistol", name: "Pistol", size: "Auxiliary", type: "CQB", damage: ["1d3 Kinetic"], range: ["Range 5", "Threat 3"], tags: ["Reliable 1"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_segment_knife", name: "Segment Knife", size: "Auxiliary", type: "Melee", damage: ["1d3+1 Energy"], range: ["Threat 1"], tags: ["Overkill "], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_tactical_knife", name: "Tactical Knife", size: "Auxiliary", type: "Melee", damage: ["1d3+1 Kinetic"], range: ["Threat 1"], tags: ["Thrown 3"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_thermal_pistol", name: "Thermal Pistol", size: "Auxiliary", type: "CQB", damage: ["2 Energy"], range: ["Line 5"], tags: [], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_anti_materiel_rifle", name: "Anti-Materiel Rifle", size: "Heavy", type: "Rifle", damage: ["2d6 Kinetic"], range: ["Range 20"], tags: ["Accurate ", "Armor-Piercing (AP)", "Loading", "Ordnance"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_heavy_charged_blade", name: "Heavy Charged Blade", size: "Heavy", type: "Melee", damage: ["1d6+3 Energy"], range: ["Threat 1"], tags: ["Armor-Piercing (AP)"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_heavy_machine_gun", name: "Heavy Machine Gun", size: "Heavy", type: "Cannon", damage: ["2d6+4 Kinetic"], range: ["Range 8"], tags: ["Inaccurate "], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_heavy_melee_weapon", name: "Heavy Melee Weapon", size: "Heavy", type: "Melee", damage: ["2d6+1 Kinetic"], range: ["Threat 1"], tags: [], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_howitzer", name: "Howitzer", size: "Heavy", type: "Cannon", damage: ["2d6 Explosive"], range: ["Range 20", "Blast 2"], tags: ["Arcing", "Inaccurate ", "Loading", "Ordnance"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_thermal_lance", name: "Thermal Lance", size: "Heavy", type: "Cannon", damage: ["1d6+3 Energy"], range: ["Line 10"], tags: ["Heat 2 (Self)"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_assault_rifle", name: "Assault Rifle", size: "Main", type: "Rifle", damage: ["1d6 Kinetic"], range: ["Range 10"], tags: ["Reliable 2"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_charged_blade", name: "Charged Blade", size: "Main", type: "Melee", damage: ["1d3+3 Energy"], range: ["Threat 1"], tags: ["Armor-Piercing (AP)"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_mortar", name: "Mortar", size: "Main", type: "Cannon", damage: ["1d6+1 Explosive"], range: ["Range 15", "Blast 1"], tags: ["Arcing", "Inaccurate "], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_nexus_hunter_killer", name: "Nexus (Hunter-Killer)", size: "Main", type: "Nexus", damage: ["1d6 Kinetic"], range: ["Range 10"], tags: ["Smart"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_rocket_propelled_grenade", name: "Rocket-Propelled Grenade", size: "Main", type: "Launcher", damage: ["1d6+1 Explosive"], range: ["Range 10", "Blast 2"], tags: ["Loading", "Ordnance"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_shotgun", name: "Shotgun", size: "Main", type: "CQB", damage: ["1d6 Kinetic"], range: ["Range 5", "Threat 3"], tags: [], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_tactical_melee_weapon", name: "Tactical Melee Weapon", size: "Main", type: "Melee", damage: ["1d6+2 Kinetic"], range: ["Threat 1"], tags: [], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_thermal_rifle", name: "Thermal Rifle", size: "Main", type: "Rifle", damage: ["1d3+2 Energy"], range: ["Range 5"], tags: ["Armor-Piercing (AP)"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_cyclone_pulse_rifle", name: "Cyclone Pulse Rifle", size: "Superheavy", type: "Rifle", damage: ["3d6+3 Kinetic"], range: ["Range 15"], tags: ["Accurate ", "Loading", "Reliable 5"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "mw_stub_cannon", name: "Stub Cannon", size: "Auxiliary", type: "Cannon", damage: ["3 Explosive"], range: ["Range 5"], tags: ["Limited 6", "Knockback 1"], manufacturer: "HA", license: "Iskander", licenseLevel: 1 },
  { id: "mw_andromeda_pattern_heavy_laser_rifle", name: "ANDROMEDA-Pattern Heavy Laser Rifle", size: "Heavy", type: "Cannon", damage: ["2d6 Energy", "3 Burn"], range: ["Range 12"], tags: ["Heat 3 (Self)"], manufacturer: "HA", license: "Sherman", licenseLevel: 2 },
  { id: "mw_gravity_gun", name: "Gravity Gun", size: "Heavy", type: "Rifle", damage: [], range: ["Range 8", "Blast 3"], tags: [], manufacturer: "HA", license: "Iskander", licenseLevel: 2 },
  { id: "mw_krakatoa_thermobaric_flamethrower", name: "Krakatoa Thermobaric Flamethrower", size: "Heavy", type: "CQB", damage: ["1 Energy", "4 Burn"], range: ["Cone 5"], tags: [], manufacturer: "HA", license: "Genghis", licenseLevel: 1 },
  { id: "mw_annihilator", name: "Annihilator", size: "Main", type: "CQB", damage: ["1d3+2 Energy"], range: ["Range 5", "Threat 3"], tags: ["Armor-Piercing (AP)", "Heat 2 (Self)"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 1 },
  { id: "mw_displacer", name: "Displacer", size: "Main", type: "Rifle", damage: ["10 Energy"], range: ["Range 10", "Blast 1"], tags: ["Armor-Piercing (AP)", "Loading", "Unique", "Heat 10 (Self)"], manufacturer: "HA", license: "Napoleon", licenseLevel: 3 },
  { id: "mw_sol_pattern_laser_rifle", name: "SOL-Pattern Laser Rifle", size: "Main", type: "Rifle", damage: ["1d6 Energy", "1 Burn"], range: ["Range 8"], tags: ["Heat 1 (Self)"], manufacturer: "HA", license: "Sherman", licenseLevel: 1 },
  { id: "mw_shatterhead_colony_missiles", name: "Shatterhead Colony Missiles", size: "Main", type: "Launcher", damage: ["1d3+1 Energy"], range: ["Range 15"], tags: ["Arcing"], manufacturer: "HA", license: "Saladin", licenseLevel: 1 },
  { id: "mw_torch", name: "Torch", size: "Main", type: "Melee", damage: ["1d6 Energy", "3 Burn"], range: ["Threat 1"], tags: ["Overkill ", "Heat 2 (Self)"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 2 },
  { id: "mw_plasma_thrower", name: "Plasma Thrower", size: "Superheavy", type: "CQB", damage: ["1d6+2 Energy", "6 Burn"], range: ["Cone 7", "Line 10"], tags: ["Heat 4 (Self)"], manufacturer: "HA", license: "Genghis", licenseLevel: 3 },
  { id: "mw_siege_cannon", name: "Siege Cannon", size: "Superheavy", type: "Cannon", damage: [], range: [], tags: [], manufacturer: "HA", license: "Barbarossa", licenseLevel: 3 },
  { id: "mw_tachyon_lance", name: "Tachyon Lance", size: "Superheavy", type: "Cannon", damage: ["2d6 Energy", "8 Burn"], range: ["Range 20"], tags: ["Ordnance", "Heat 4 (Self)"], manufacturer: "HA", license: "Sherman", licenseLevel: 3 },
  { id: "mw_catalyst_pistol", name: "Catalyst Pistol", size: "Auxiliary", type: "CQB", damage: ["1d3 Energy"], range: ["Cone 3", "Threat 3"], tags: ["Heat 2 (Self)"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 1 },
  { id: "mw_arc_projector", name: "Arc Projector", size: "Heavy", type: "CQB", damage: ["1d6+1 Energy"], range: ["Range 5"], tags: ["Heat 1 (Self)"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 2 },
  { id: "mw_ghast_nexus", name: "Ghast Nexus", size: "Heavy", type: "Nexus", damage: ["1d6+3 Explosive"], range: ["Range 10"], tags: ["Smart"], manufacturer: "HORUS", license: "Hydra", licenseLevel: 2 },
  { id: "mw_mimic_gun", name: "Mimic Gun", size: "Heavy", type: "???", damage: ["??? Kinetic"], range: ["Range ???"], tags: [], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 2 },
  { id: "mw_nanobot_whip", name: "Nanobot Whip", size: "Heavy", type: "Melee", damage: ["2d6 Kinetic"], range: ["Threat 3"], tags: ["Smart"], manufacturer: "HORUS", license: "Balor", licenseLevel: 3 },
  { id: "mw_autogun", name: "Autogun", size: "Main", type: "Cannon", damage: ["3 Kinetic"], range: ["Range 15"], tags: [], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 3 },
  { id: "mw_autopod", name: "Autopod", size: "Main", type: "Launcher", damage: ["3 Kinetic"], range: ["Range 15"], tags: ["Seeking", "Unique"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 1 },
  { id: "mw_ghoul_nexus", name: "Ghoul Nexus", size: "Main", type: "Nexus", damage: ["1d3+2 Variable"], range: ["Range 10"], tags: ["Smart", "Set Damage Type"], manufacturer: "HORUS", license: "Hydra", licenseLevel: 1 },
  { id: "mw_smartgun", name: "Smartgun", size: "Main", type: "Rifle", damage: ["4 Kinetic"], range: ["Range 15"], tags: ["Accurate ", "Seeking", "Smart"], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 1 },
  { id: "mw_swarm_hive_nanites", name: "Swarm/Hive Nanites", size: "Main", type: "Nexus", damage: ["2 Kinetic", "2 Burn"], range: ["Range 5"], tags: ["Smart", "Seeking"], manufacturer: "HORUS", license: "Balor", licenseLevel: 3 },
  { id: "mw_vorpal_gun", name: "Vorpal Gun", size: "Main", type: "Cannon", damage: ["2d6 Kinetic"], range: ["Range 5"], tags: [], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 3 },
  { id: "mw_annihilation_nexus", name: "Annihilation Nexus", size: "Superheavy", type: "Nexus", damage: ["1d6+3 Energy"], range: ["Burst 2"], tags: ["Armor-Piercing (AP)", "Smart"], manufacturer: "HORUS", license: "Hydra", licenseLevel: 3 },
  { id: "mw_bristlecrown_flechette_launcher", name: "Bristlecrown Flechette Launcher", size: "Auxiliary", type: "CQB", damage: ["1 Kinetic"], range: ["Burst 1"], tags: [], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 2 },
  { id: "mw_cutter_mkii_plasma_torch", name: "Cutter MkII Plasma Torch", size: "Auxiliary", type: "Melee", damage: ["1 Energy", "1 Heat", "1 Burn"], range: ["Threat 1"], tags: ["Heat 1 (Self)"], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 3 },
  { id: "mw_hand_cannon", name: "Hand Cannon", size: "Auxiliary", type: "CQB", damage: ["1d6 Kinetic"], range: ["Range 5", "Threat 3"], tags: ["Loading", "Reliable 1"], manufacturer: "IPS-N", license: "Raleigh", licenseLevel: 1 },
  { id: "mw_power_knuckles", name: "Power Knuckles", size: "Auxiliary", type: "Melee", damage: ["1d3+1 Explosive"], range: ["Threat 1"], tags: [], manufacturer: "IPS-N", license: "Nelson", licenseLevel: 3 },
  { id: "mw_bolt_thrower", name: "Bolt Thrower", size: "Heavy", type: "Cannon", damage: ["2d6 Kinetic", "1d6 Explosive"], range: ["Range 8"], tags: ["Loading", "Reliable 2"], manufacturer: "IPS-N", license: "Raleigh", licenseLevel: 2 },
  { id: "mw_daisy_cutter", name: "Daisy Cutter", size: "Heavy", type: "CQB", damage: ["3d6 Kinetic"], range: ["Cone 7"], tags: ["Limited 2"], manufacturer: "IPS-N", license: "Tortuga", licenseLevel: 2 },
  { id: "mw_kinetic_hammer", name: "Kinetic Hammer", size: "Heavy", type: "Melee", damage: ["2d6+2 Kinetic"], range: ["Threat 1"], tags: ["Reliable 4"], manufacturer: "IPS-N", license: "Raleigh", licenseLevel: 3 },
  { id: "mw_nanocarbon_sword", name: "Nanocarbon Sword", size: "Heavy", type: "Melee", damage: ["1d6+4 Kinetic"], range: ["Threat 2"], tags: ["Reliable 3"], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 2 },
  { id: "mw_assault_cannon", name: "Assault Cannon", size: "Main", type: "Cannon", damage: [], range: [], tags: [], manufacturer: "IPS-N", license: "Drake", licenseLevel: 1 },
  { id: "mw_catalytic_hammer", name: "Catalytic Hammer", size: "Main", type: "Melee", damage: ["1d3+5 Kinetic"], range: ["Threat 1"], tags: ["Loading"], manufacturer: "IPS-N", license: "Tortuga", licenseLevel: 2 },
  { id: "mw_chain_axe", name: "Chain Axe", size: "Main", type: "Melee", damage: ["1d6 Kinetic"], range: ["Threat 1"], tags: ["Reliable 2"], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 1 },
  { id: "mw_concussion_missiles", name: "Concussion Missiles", size: "Main", type: "Launcher", damage: ["1d3 Explosive"], range: ["Range 5"], tags: ["Knockback 2"], manufacturer: "IPS-N", license: "Drake", licenseLevel: 2 },
  { id: "mw_deck_sweeper_automatic_shotgun", name: "Deck-Sweeper Automatic Shotgun", size: "Main", type: "CQB", damage: ["2d6 Kinetic"], range: ["Range 3", "Threat 3"], tags: ["Inaccurate "], manufacturer: "IPS-N", license: "Tortuga", licenseLevel: 1 },
  { id: "mw_impact_lance", name: "Impact Lance", size: "Main", type: "Melee", damage: ["1d6 Energy"], range: ["Threat 3"], tags: [], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 1 },
  { id: "mw_impaler_nailgun", name: "Impaler Nailgun", size: "Main", type: "CQB", damage: ["1d6+1 Kinetic"], range: ["Range 5", "Threat 3"], tags: ["Heat 1 (Self)"], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 2 },
  { id: "mw_war_pike", name: "War Pike", size: "Main", type: "Melee", damage: ["1d6 Kinetic"], range: ["Threat 3"], tags: ["Knockback 1", "Thrown 5"], manufacturer: "IPS-N", license: "Nelson", licenseLevel: 1 },
  { id: "mw_combat_drill", name: "Combat Drill", size: "Superheavy", type: "Melee", damage: ["3d6 Kinetic", "1d6 Energy"], range: ["Threat 1"], tags: ["Armor-Piercing (AP)", "Overkill "], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 3 },
  { id: "mw_leviathan_heavy_assault_cannon", name: "Leviathan Heavy Assault Cannon", size: "Superheavy", type: "Cannon", damage: [], range: [], tags: [], manufacturer: "IPS-N", license: "Drake", licenseLevel: 3 },
  { id: "mw_fold_knife", name: "Fold Knife", size: "Auxiliary", type: "Melee", damage: ["1d3 Kinetic"], range: ["Threat 1"], tags: ["Accurate "], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 1 },
  { id: "mw_oracle_lmg_i", name: "Oracle LMG-I", size: "Auxiliary", type: "Rifle", damage: ["1d3 Kinetic"], range: ["Range 15"], tags: ["Accurate ", "Arcing"], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 2 },
  { id: "mw_shock_knife", name: "Shock Knife", size: "Auxiliary", type: "Melee", damage: ["1 Energy", "2 Burn"], range: ["Threat 1"], tags: ["Thrown 5", "Heat 1 (Self)"], manufacturer: "SSC", license: "Metalmark", licenseLevel: 2 },
  { id: "mw_vijaya_rockets", name: "Vijaya Rockets", size: "Auxiliary", type: "Launcher", damage: ["1d3 Explosive"], range: ["Range 5"], tags: ["Accurate "], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 1 },
  { id: "mw_gandiva_missiles", name: "Gandiva Missiles", size: "Heavy", type: "Launcher", damage: ["1d6+3 Energy"], range: ["Range 15"], tags: ["Accurate ", "Seeking", "Smart"], manufacturer: "SSC", license: "Monarch", licenseLevel: 2 },
  { id: "mw_railgun", name: "Railgun", size: "Heavy", type: "Rifle", damage: ["1d6+4 Kinetic"], range: ["Line 20"], tags: ["Armor-Piercing (AP)", "Ordnance", "Heat 2 (Self)"], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 3 },
  { id: "mw_burst_launcher", name: "Burst Launcher", size: "Main", type: "Launcher", damage: ["1d3 Explosive", "1 Heat"], range: ["Range 15"], tags: ["Accurate ", "Arcing"], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 2 },
  { id: "mw_magnetic_cannon", name: "Magnetic Cannon", size: "Main", type: "Cannon", damage: ["1d3+1 Energy"], range: ["Line 8"], tags: [], manufacturer: "SSC", license: "Black Witch", licenseLevel: 1 },
  { id: "mw_rail_rifle", name: "Rail Rifle", size: "Main", type: "Rifle", damage: ["1d6+1 Kinetic"], range: ["Line 10"], tags: ["Heat 1 (Self)"], manufacturer: "SSC", license: "Metalmark", licenseLevel: 2 },
  { id: "mw_sharanga_missiles", name: "Sharanga Missiles", size: "Main", type: "Launcher", damage: ["3 Explosive"], range: ["Range 15"], tags: ["Arcing"], manufacturer: "SSC", license: "Monarch", licenseLevel: 1 },
  { id: "mw_variable_sword", name: "Variable Sword", size: "Main", type: "Melee", damage: ["3 Kinetic"], range: ["Threat 2"], tags: ["Accurate "], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 3 },
  { id: "mw_veil_rifle", name: "Veil Rifle", size: "Main", type: "Rifle", damage: ["1d3+1 Energy"], range: ["Line 10"], tags: ["Accurate "], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 1 },
  { id: "mw_vulture_dmr", name: "Vulture DMR", size: "Main", type: "Rifle", damage: ["1d6+1 Kinetic"], range: ["Range 15"], tags: ["Accurate ", "Overkill ", "Heat 1 (Self)"], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 2 },
  { id: "mw_pinaka_missiles", name: "Pinaka Missiles", size: "Superheavy", type: "Launcher", damage: ["2d6 Explosive"], range: ["Range 20", "Blast 1"], tags: ["Arcing", "Heat 2 (Self)"], manufacturer: "SSC", license: "Monarch", licenseLevel: 3 },
];

export const LANCER_SYSTEMS: LancerSystem[] = [
  { id: "ms_walking_armory_1", name: "Ammo Case I", type: "", sp: 0, tags: ["Limited 6", "1/Turn"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_walking_armory_2", name: "Ammo Case II", type: "", sp: 0, tags: ["Limited 6", "1/Turn"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_walking_armory_3", name: "Ammo Case III", type: "", sp: 0, tags: ["Limited 6", "1/Turn"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_technophile_3", name: "Enlightenment-Class NHP", type: "AI", sp: 0, tags: ["Unique", "1/Round", "AI"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_technophile_1", name: "Servant-Class NHP", type: "AI", sp: 0, tags: ["AI", "Unique"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_technophile_2", name: "Student-Class NHP", type: "AI", sp: 0, tags: ["AI", "Unique", "1/Round"], manufacturer: "", license: "GMS", licenseLevel: 0 },
  { id: "ms_comp_con_class_assistant_unit", name: "COMP/CON-Class Assistant Unit", type: "AI", sp: 2, tags: ["AI", "Prevent Cascade", "Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_custom_paint_job", name: "Custom Paint Job", type: "", sp: 1, tags: ["Unique", "Indestructible"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_eva_module", name: "EVA Module", type: "Flight System", sp: 1, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_expanded_compartment", name: "Expanded Compartment", type: "", sp: 1, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_manipulators", name: "Manipulators", type: "", sp: 1, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_pattern_a_jericho_deployable_cover", name: "Pattern-A Jericho Deployable Cover", type: "Deployable", sp: 2, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_pattern_a_smoke_charges", name: "Pattern-A Smoke Charges", type: "Deployable", sp: 2, tags: ["Limited 3", "Unique", "Grenade"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_pattern_b_hex_charges", name: "Pattern-B HEX Charges", type: "Deployable", sp: 2, tags: ["Limited 3", "Unique", "Grenade"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_personalizations", name: "Personalizations", type: "", sp: 1, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_rapid_burst_jump_jet_system", name: "Rapid Burst Jump Jet System", type: "Flight System", sp: 2, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_stable_structure", name: "Stable Structure", type: "", sp: 2, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_turret_drones", name: "Turret Drones", type: "Drone", sp: 2, tags: ["Limited 3", "Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_type_3_projected_shield", name: "Type-3 Projected Shield", type: "Shield", sp: 2, tags: ["Shield", "Unique", "Heat 1 (Self)"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_type_i_flight_system", name: "Type-I Flight System", type: "Flight System", sp: 3, tags: ["Unique"], manufacturer: "GMS", license: "GMS", licenseLevel: 0 },
  { id: "ms_agni_class_nhp", name: "AGNI-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "Limited 1"], manufacturer: "HA", license: "Genghis", licenseLevel: 3 },
  { id: "ms_asura_class_nhp", name: "ASURA-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "Limited 1", "Heat 3 (Self)"], manufacturer: "HA", license: "Sherman", licenseLevel: 3 },
  { id: "ms_auto_cooler", name: "Auto-Cooler", type: "", sp: 2, tags: ["Unique"], manufacturer: "HA", license: "Genghis", licenseLevel: 2 },
  { id: "ms_autoloader_drone", name: "Autoloader Drone", type: "Drone", sp: 2, tags: ["Limited 1", "Unique"], manufacturer: "HA", license: "Barbarossa", licenseLevel: 2 },
  { id: "ms_blinkshield", name: "Blinkshield", type: "Shield", sp: 2, tags: ["Unique", "Shield", "Heat 4 (Self)"], manufacturer: "HA", license: "Napoleon", licenseLevel: 3 },
  { id: "ms_clamp_bombs", name: "Clamp Bombs", type: "", sp: 2, tags: ["Limited 4", "Unique"], manufacturer: "HA", license: "Iskander", licenseLevel: 3 },
  { id: "ms_deep_well_heat_sink", name: "Deep Well Heat Sink", type: "", sp: 4, tags: ["Unique"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 2 },
  { id: "ms_enclave_pattern_support_shield", name: "ENCLAVE-Pattern Support Shield", type: "Shield", sp: 2, tags: ["Unique", "Shield"], manufacturer: "HA", license: "Saladin", licenseLevel: 1 },
  { id: "ms_explosive_vents", name: "Explosive Vents", type: "", sp: 2, tags: ["Unique", "1/Round"], manufacturer: "HA", license: "Genghis", licenseLevel: 1 },
  { id: "ms_external_ammo_feed", name: "External Ammo Feed", type: "", sp: 3, tags: ["Unique", "Heat 1d3+1 (Self)"], manufacturer: "HA", license: "Barbarossa", licenseLevel: 3 },
  { id: "ms_external_batteries", name: "External Batteries", type: "", sp: 2, tags: ["Unique"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 1 },
  { id: "ms_flak_launcher", name: "Flak Launcher", type: "", sp: 2, tags: [], manufacturer: "HA", license: "Barbarossa", licenseLevel: 2 },
  { id: "ms_flash_anchor", name: "Flash Anchor", type: "Shield", sp: 1, tags: ["Unique", "Shield", "Heat 2 (Self)"], manufacturer: "HA", license: "Saladin", licenseLevel: 2 },
  { id: "ms_grounding_charges", name: "Grounding Charges", type: "Deployable", sp: 2, tags: ["Limited 2", "Unique", "Grenade"], manufacturer: "HA", license: "Iskander", licenseLevel: 1 },
  { id: "ms_havok_charges", name: "HAVOK Charges", type: "Deployable", sp: 2, tags: ["Limited 2", "Unique", "Grenade"], manufacturer: "HA", license: "Genghis", licenseLevel: 2 },
  { id: "ms_hardlight_defense_system", name: "Hardlight Defense System", type: "Shield", sp: 3, tags: ["Unique", "Shield", "Heat 2 (Self)"], manufacturer: "HA", license: "Saladin", licenseLevel: 2 },
  { id: "ms_lucifer_class_nhp", name: "LUCIFER-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "Limited 2", "Heat 1d3+3 (Self)"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 3 },
  { id: "ms_noah_class_nhp", name: "NOAH-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique"], manufacturer: "HA", license: "Saladin", licenseLevel: 3 },
  { id: "ms_plasma_gauntlet", name: "Plasma Gauntlet", type: "", sp: 2, tags: ["Danger Zone", "Limited 1", "Unique"], manufacturer: "HA", license: "Tokugawa", licenseLevel: 3 },
  { id: "ms_reactor_stabilizer", name: "Reactor Stabilizer", type: "", sp: 3, tags: ["Unique"], manufacturer: "HA", license: "Sherman", licenseLevel: 1 },
  { id: "ms_redundant_systems_upgrade", name: "Redundant Systems Upgrade", type: "", sp: 3, tags: ["Limited 1", "Unique"], manufacturer: "HA", license: "Sherman", licenseLevel: 2 },
  { id: "ms_repulser_field", name: "Repulser Field", type: "", sp: 1, tags: ["Unique", "Heat 1 (Self)"], manufacturer: "HA", license: "Iskander", licenseLevel: 2 },
  { id: "ms_siege_stabilizers", name: "Siege Stabilizers", type: "", sp: 1, tags: ["Unique"], manufacturer: "HA", license: "Barbarossa", licenseLevel: 1 },
  { id: "ms_stasis_barrier", name: "Stasis Barrier", type: "Deployable", sp: 2, tags: ["Limited 1", "Shield", "Unique", "Invulnerable"], manufacturer: "HA", license: "Napoleon", licenseLevel: 2 },
  { id: "ms_stasis_bolt", name: "Stasis Bolt", type: "Shield", sp: 1, tags: ["Shield", "Unique"], manufacturer: "HA", license: "Napoleon", licenseLevel: 1 },
  { id: "ms_stasis_generator", name: "Stasis Generator", type: "Shield", sp: 2, tags: ["Unique", "Shield"], manufacturer: "HA", license: "Napoleon", licenseLevel: 1 },
  { id: "ms_tesseract", name: "Tesseract", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HA", license: "Iskander", licenseLevel: 3 },
  { id: "ms_roller_directed_payload_charges", name: "“Roller” Directed Payload Charges", type: "Deployable", sp: 2, tags: ["Limited 2", "Unique", "Grenade"], manufacturer: "HA", license: "Barbarossa", licenseLevel: 1 },
  { id: "ms___scorpion_v70.1", name: "//SCORPION V70.1", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 2 },
  { id: "ms_aggressive_system_sync", name: "Aggressive System Sync", type: "Tech", sp: 2, tags: [], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 2 },
  { id: "ms_assassin_drone", name: "Assassin Drone", type: "Drone", sp: 2, tags: [], manufacturer: "HORUS", license: "Hydra", licenseLevel: 3 },
  { id: "ms_beckoner", name: "Beckoner", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 1 },
  { id: "ms_emp_pulse", name: "EMP Pulse", type: "", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 3 },
  { id: "ms_eye_of_horus", name: "Eye of HORUS", type: "", sp: 3, tags: ["Unique"], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 2 },
  { id: "ms_h0r_os_system_upgrade_i", name: "H0R_OS System Upgrade I", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 1 },
  { id: "ms_h0r_os_system_upgrade_ii", name: "H0R_OS System Upgrade II", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 2 },
  { id: "ms_h0r_os_system_upgrade_iii", name: "H0R_OS System Upgrade III", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 3 },
  { id: "ms_hive_drone", name: "Hive Drone", type: "Drone", sp: 2, tags: [], manufacturer: "HORUS", license: "Balor", licenseLevel: 1 },
  { id: "ms_hunter_lock", name: "Hunter Lock", type: "", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 1 },
  { id: "ms_interdiction_field", name: "Interdiction Field", type: "", sp: 3, tags: [], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 3 },
  { id: "ms_law_of_blades", name: "Law of Blades", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 3 },
  { id: "ms_lightning_generator", name: "Lightning Generator", type: "", sp: 3, tags: ["Unique", "Heat 1 (Self)"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 3 },
  { id: "ms_mesmer_charges", name: "Mesmer Charges", type: "Deployable", sp: 2, tags: ["Limited 2", "Unique", "Grenade"], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 1 },
  { id: "ms_metafold_carver", name: "Metafold Carver", type: "Tech", sp: 2, tags: [], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 2 },
  { id: "ms_metahook", name: "Metahook", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 2 },
  { id: "ms_mimic_mesh", name: "Mimic Mesh", type: "", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 1 },
  { id: "ms_monitor_module", name: "Monitor Module", type: "", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 2 },
  { id: "ms_osiris_class_nhp", name: "OSIRIS-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "1/Round"], manufacturer: "HORUS", license: "Goblin", licenseLevel: 3 },
  { id: "ms_puppetmaster", name: "PUPPETMASTER", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Hydra", licenseLevel: 1 },
  { id: "ms_scylla_class_nhp", name: "SCYLLA-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "Heat 2 (Self)"], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 3 },
  { id: "ms_sisyphus_class_nhp", name: "SISYPHUS-Class NHP", type: "AI", sp: 2, tags: ["AI", "Unique", "2/Round"], manufacturer: "HORUS", license: "Pegasus", licenseLevel: 3 },
  { id: "ms_scanner_swarm", name: "Scanner Swarm", type: "Tech", sp: 1, tags: ["Unique"], manufacturer: "HORUS", license: "Balor", licenseLevel: 1 },
  { id: "ms_sentinel_drone", name: "Sentinel Drone", type: "Drone", sp: 2, tags: [], manufacturer: "HORUS", license: "Gorgon", licenseLevel: 1 },
  { id: "ms_smite", name: "Smite", type: "Tech", sp: 3, tags: ["Unique"], manufacturer: "HORUS", license: "Manticore", licenseLevel: 2 },
  { id: "ms_swarm_body", name: "Swarm Body", type: "", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Balor", licenseLevel: 2 },
  { id: "ms_tempest_drone", name: "Tempest Drone", type: "Drone", sp: 2, tags: ["Resistance (All)"], manufacturer: "HORUS", license: "Hydra", licenseLevel: 2 },
  { id: "ms_viral_logic_suite", name: "Viral Logic Suite", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "HORUS", license: "Minotaur", licenseLevel: 1 },
  { id: "ms_aceso_stabilizer", name: "Aceso Stabilizer", type: "Shield", sp: 3, tags: ["Limited 3", "Overshield", "Shield", "Unique"], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 3 },
  { id: "ms_aegis_shield_generator", name: "Aegis Shield Generator", type: "Deployable", sp: 2, tags: ["Unique", "Limited 1"], manufacturer: "IPS-N", license: "Drake", licenseLevel: 2 },
  { id: "ms_argonaut_shield", name: "Argonaut Shield", type: "", sp: 2, tags: ["Unique"], manufacturer: "IPS-N", license: "Drake", licenseLevel: 1 },
  { id: "ms_armor_lock_plating", name: "Armor-Lock Plating", type: "", sp: 1, tags: ["Unique", "Heat 2 (Self)"], manufacturer: "IPS-N", license: "Nelson", licenseLevel: 2 },
  { id: "ms_bb_breach_blast_charges", name: "BB Breach/Blast Charges", type: "Deployable", sp: 2, tags: ["Limited 3", "Unique", "Grenade"], manufacturer: "IPS-N", license: "Raleigh", licenseLevel: 1 },
  { id: "ms_bulwark_mods", name: "Bulwark Mods", type: "", sp: 1, tags: ["Unique"], manufacturer: "IPS-N", license: "Nelson", licenseLevel: 1 },
  { id: "ms_cable_winch_system", name: "Cable Winch System", type: "", sp: 1, tags: [], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 1 },
  { id: "ms_caltrop_launcher", name: "Caltrop Launcher", type: "", sp: 1, tags: ["Unique"], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 2 },
  { id: "ms_charged_stake", name: "Charged Stake", type: "", sp: 2, tags: [], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 3 },
  { id: "ms_hyperdense_armor", name: "HyperDense Armor", type: "Shield", sp: 3, tags: ["Unique", "Shield"], manufacturer: "IPS-N", license: "Tortuga", licenseLevel: 3 },
  { id: "ms_mule_harness", name: "MULE Harness", type: "", sp: 2, tags: ["Unique"], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 2 },
  { id: "ms_portable_bunker", name: "Portable Bunker", type: "Deployable", sp: 2, tags: ["Limited 1", "Unique"], manufacturer: "IPS-N", license: "Drake", licenseLevel: 3 },
  { id: "ms_ramjet", name: "Ramjet", type: "", sp: 3, tags: ["Unique", "Heat 2 (Self)"], manufacturer: "IPS-N", license: "Nelson", licenseLevel: 3 },
  { id: "ms_reinforced_cabling", name: "Reinforced Cabling", type: "", sp: 2, tags: [], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 3 },
  { id: "ms_restock_drone", name: "Restock Drone", type: "Drone", sp: 2, tags: ["Limited 2", "Unique"], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 1 },
  { id: "ms_sekhmet_class_nhp", name: "SEKHMET-Class NHP", type: "AI", sp: 3, tags: ["Unique", "AI"], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 3 },
  { id: "ms_siege_ram", name: "Siege Ram", type: "", sp: 2, tags: ["Unique"], manufacturer: "IPS-N", license: "Tortuga", licenseLevel: 1 },
  { id: "ms_synthetic_muscle_netting", name: "Synthetic Muscle Netting", type: "", sp: 2, tags: ["Unique"], manufacturer: "IPS-N", license: "Blackbeard", licenseLevel: 1 },
  { id: "ms_webjaw_snare", name: "Webjaw Snare", type: "Deployable", sp: 1, tags: ["Limited 2", "Unique"], manufacturer: "IPS-N", license: "Vlad", licenseLevel: 1 },
  { id: "ms_whitewash_sealant_spray", name: "Whitewash Sealant Spray", type: "", sp: 2, tags: [], manufacturer: "IPS-N", license: "Lancaster", licenseLevel: 2 },
  { id: "ms_roland_chamber", name: "“Roland” Chamber", type: "", sp: 3, tags: ["Unique"], manufacturer: "IPS-N", license: "Raleigh", licenseLevel: 2 },
  { id: "ms_athena_class_nhp", name: "ATHENA-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique"], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 3 },
  { id: "ms_active_camouflage", name: "Active Camouflage", type: "", sp: 3, tags: ["Unique", "Heat 2 (Self)"], manufacturer: "SSC", license: "Metalmark", licenseLevel: 3 },
  { id: "ms_black_ice_module", name: "Black ICE Module", type: "Tech", sp: 3, tags: ["Unique"], manufacturer: "SSC", license: "Black Witch", licenseLevel: 3 },
  { id: "ms_core_siphon", name: "Core Siphon", type: "", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 2 },
  { id: "ms_fade_cloak", name: "FADE Cloak", type: "", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 3 },
  { id: "ms_ferrous_lash", name: "Ferrous Lash", type: "", sp: 2, tags: [], manufacturer: "SSC", license: "Black Witch", licenseLevel: 1 },
  { id: "ms_flash_charges", name: "Flash Charges", type: "Deployable", sp: 2, tags: ["Limited 2", "Unique", "Grenade"], manufacturer: "SSC", license: "Metalmark", licenseLevel: 1 },
  { id: "ms_flicker_field_projector", name: "Flicker Field Projector", type: "", sp: 1, tags: ["Unique"], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 2 },
  { id: "ms_high_stress_mag_clamps", name: "High-Stress Mag Clamps", type: "", sp: 1, tags: ["Unique"], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 1 },
  { id: "ms_hunter_logic_suite", name: "Hunter Logic Suite", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 2 },
  { id: "ms_iceout_drone", name: "ICEOUT Drone", type: "Drone", sp: 2, tags: ["Limited 2", "Unique"], manufacturer: "SSC", license: "Black Witch", licenseLevel: 2 },
  { id: "ms_javelin_rockets", name: "Javelin Rockets", type: "", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Monarch", licenseLevel: 1 },
  { id: "ms_kinetic_compensator", name: "Kinetic Compensator", type: "", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 3 },
  { id: "ms_lb_oc_cloaking_field", name: "LB/OC Cloaking Field", type: "", sp: 4, tags: ["Heat 2 (Self)"], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 3 },
  { id: "ms_lotus_projector", name: "Lotus Projector", type: "Drone", sp: 2, tags: ["Invisible"], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 1 },
  { id: "ms_magnetic_shield", name: "Magnetic Shield", type: "Shield", sp: 2, tags: ["Shield", "Unique"], manufacturer: "SSC", license: "Black Witch", licenseLevel: 3 },
  { id: "ms_markerlight", name: "Markerlight", type: "Tech", sp: 2, tags: [], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 1 },
  { id: "ms_neurospike", name: "Neurospike", type: "Tech", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 1 },
  { id: "ms_oasis_wall", name: "OASIS Wall", type: "Shield", sp: 3, tags: ["Unique", "Shield", "Heat 2 (Self)"], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 3 },
  { id: "ms_perimeter_command_plate", name: "Perimeter Command Plate", type: "Deployable", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Black Witch", licenseLevel: 2 },
  { id: "ms_reactive_weave", name: "Reactive Weave", type: "", sp: 1, tags: ["Unique"], manufacturer: "SSC", license: "Metalmark", licenseLevel: 1 },
  { id: "ms_retractable_profile", name: "Retractable Profile", type: "Tech", sp: 1, tags: ["Unique"], manufacturer: "SSC", license: "Swallowtail", licenseLevel: 2 },
  { id: "ms_singularity_motivator", name: "Singularity Motivator", type: "", sp: 2, tags: ["Unique"], manufacturer: "SSC", license: "Mourning Cloak", licenseLevel: 2 },
  { id: "ms_stuncrown", name: "StunCrown", type: "", sp: 2, tags: ["Limited 2", "Unique"], manufacturer: "SSC", license: "Dusk Wing", licenseLevel: 3 },
  { id: "ms_tlaloc_class_nhp", name: "TLALOC-Class NHP", type: "AI", sp: 3, tags: ["AI", "Unique", "Heat 2 (Self)"], manufacturer: "SSC", license: "Monarch", licenseLevel: 3 },
  { id: "ms_tracking_bug", name: "Tracking Bug", type: "Tech", sp: 2, tags: [], manufacturer: "SSC", license: "Death’s Head", licenseLevel: 1 },
];

export const LANCER_MODS: LancerMod[] = [
  { id: "wm_paracausal_mod", name: "Paracausal Mod", sp: 4, allowedTypes: ["Melee", "CQB", "Rifle", "Launcher", "Cannon", "Nexus"], restrictedSizes: [], addedTags: ["Overkill ", "Irreducible"], addedRange: [], license: "Saladin", licenseLevel: 3 },
  { id: "wm_phase_ready_mod", name: "Phase-Ready Mod", sp: 2, allowedTypes: ["Melee", "CQB", "Rifle", "Launcher", "Cannon", "Nexus"], restrictedSizes: [], addedTags: [], addedRange: [], license: "Napoleon", licenseLevel: 2 },
  { id: "wm_nanocomposite_adaptation", name: "Nanocomposite Adaptation", sp: 2, allowedTypes: ["Melee", "CQB", "Rifle", "Launcher", "Cannon", "Nexus"], restrictedSizes: [], addedTags: ["Smart", "Seeking"], addedRange: [], license: "Balor", licenseLevel: 2 },
  { id: "wm_thermal_charge", name: "Thermal Charge", sp: 2, allowedTypes: ["Melee"], restrictedSizes: [], addedTags: [], addedRange: [], license: "Nelson", licenseLevel: 2 },
  { id: "wm_throughbolt_rounds", name: "Throughbolt Rounds", sp: 2, allowedTypes: ["CQB", "Cannon", "Rifle"], restrictedSizes: [], addedTags: [], addedRange: [], license: "Tortuga", licenseLevel: 3 },
  { id: "wm_uncle_class_comp_con", name: "UNCLE-Class Comp/Con", sp: 3, allowedTypes: ["Melee", "CQB", "Rifle", "Launcher", "Cannon", "Nexus"], restrictedSizes: ["Superheavy"], addedTags: [], addedRange: [], license: "Raleigh", licenseLevel: 3 },
  { id: "wm_shock_wreath", name: "Shock Wreath", sp: 2, allowedTypes: ["Melee"], restrictedSizes: [], addedTags: [], addedRange: [], license: "Metalmark", licenseLevel: 3 },
  { id: "wm_stabilizer_mod", name: "Stabilizer Mod", sp: 2, allowedTypes: ["Launcher", "Cannon"], restrictedSizes: [], addedTags: ["Ordnance"], addedRange: ["Range 5"], license: "Monarch", licenseLevel: 2 },
];
