// Draw Steel complications (MCDM Draw Steel Rules Reference, via the Steel Compendium data set, used
// under the Draw Steel Creator License). A complication is OPTIONAL: a hero may take one, gaining a
// benefit and a drawback. MECHANICS ONLY: this stores each complication's name plus a short tag for the
// benefit and the drawback that is DERIVED from the mechanical shape (e.g. "starting treasure",
// "fire weakness", "Renown capped") - never MCDM's benefit/drawback prose, which the player reads on the
// complication's page in the SRD. Many complications are narrative and have no clean tag; those carry an
// empty string and the Forge shows just the name. See lib/systems/drawsteel.ts for attribution.

export interface DSComplication {
  id: string;
  name: string;
  benefit: string;   // short derived tag, or "" when the benefit does not reduce to one
  drawback: string;  // short derived tag, or "" when the drawback does not reduce to one
}

export const DS_COMPLICATIONS: DSComplication[] = [
  { id: "advanced-studies", name: "Advanced Studies", benefit: "", drawback: "" },
  { id: "amnesia", name: "Amnesia", benefit: "starting treasure", drawback: "bane on lore tests" },
  { id: "animal-form", name: "Animal Form", benefit: "", drawback: "" },
  { id: "antihero", name: "Antihero", benefit: "", drawback: "bane on some tests" },
  { id: "artifact-bonded", name: "Artifact Bonded", benefit: "starting treasure, boosts recoveries/stamina", drawback: "" },
  { id: "bereaved", name: "Bereaved", benefit: "", drawback: "corruption weakness" },
  { id: "betrothed", name: "Betrothed", benefit: "starting treasure", drawback: "Renown capped" },
  { id: "chaos-touched", name: "Chaos Touched", benefit: "an edge on tests", drawback: "bane on some tests" },
  { id: "chosen-one", name: "Chosen One", benefit: "", drawback: "" },
  { id: "consuming-interest", name: "Consuming Interest", benefit: "1 skill (lore)", drawback: "" },
  { id: "corrupted-mentor", name: "Corrupted Mentor", benefit: "grants an ability", drawback: "holy weakness" },
  { id: "coward", name: "Coward", benefit: "", drawback: "" },
  { id: "crash-landed", name: "Crash Landed", benefit: "skill (lore)", drawback: "bane on some tests" },
  { id: "cult-victim", name: "Cult Victim", benefit: "", drawback: "corruption weakness" },
  { id: "curse-of-caution", name: "Curse of Caution", benefit: "", drawback: "speed penalty" },
  { id: "curse-of-immortality", name: "Curse of Immortality", benefit: "boosts recoveries/stamina", drawback: "bane on lore tests" },
  { id: "curse-of-misfortune", name: "Curse of Misfortune", benefit: "", drawback: "" },
  { id: "curse-of-poverty", name: "Curse of Poverty", benefit: "", drawback: "" },
  { id: "curse-of-punishment", name: "Curse of Punishment", benefit: "", drawback: "" },
  { id: "curse-of-stone", name: "Curse of Stone", benefit: "", drawback: "sonic weakness" },
  { id: "cursed-weapon", name: "Cursed Weapon", benefit: "starting treasure", drawback: "damage weakness" },
  { id: "disgraced", name: "Disgraced", benefit: "1 skill (interpersonal/intrigue)", drawback: "" },
  { id: "dragon-dreams", name: "Dragon Dreams", benefit: "", drawback: "" },
  { id: "elemental-inside", name: "Elemental Inside", benefit: "boosts recoveries/stamina", drawback: "" },
  { id: "evanesceria", name: "Evanesceria", benefit: "", drawback: "" },
  { id: "exile", name: "Exile", benefit: "+language", drawback: "" },
  { id: "fallen-immortal", name: "Fallen Immortal", benefit: "skill (lore), grants an ability", drawback: "bane on some tests" },
  { id: "famous-relative", name: "Famous Relative", benefit: "starting treasure, an edge on tests", drawback: "" },
  { id: "feytouched", name: "Feytouched", benefit: "", drawback: "" },
  { id: "fiery-ideal", name: "Fiery Ideal", benefit: "", drawback: "" },
  { id: "fire-and-chaos", name: "Fire and Chaos", benefit: "fire immunity", drawback: "cold weakness" },
  { id: "following-in-the-footsteps", name: "Following in the Footsteps", benefit: "", drawback: "" },
  { id: "forbidden-romance", name: "Forbidden Romance", benefit: "", drawback: "" },
  { id: "frostheart", name: "Frostheart", benefit: "cold immunity", drawback: "fire weakness" },
  { id: "getting-too-old-for-this", name: "Getting Too Old for This", benefit: "grants an ability", drawback: "speed penalty" },
  { id: "gnoll-mauled", name: "Gnoll-Mauled", benefit: "boosts recoveries/stamina", drawback: "" },
  { id: "greening", name: "Greening", benefit: "corruption immunity", drawback: "fire weakness" },
  { id: "grifter", name: "Grifter", benefit: "1 skill (intrigue)", drawback: "" },
  { id: "grounded", name: "Grounded", benefit: "grants an ability", drawback: "" },
  { id: "guilty-conscience", name: "Guilty Conscience", benefit: "boosts recoveries/stamina", drawback: "bane on some tests" },
  { id: "hawk-rider", name: "Hawk Rider", benefit: "boosts recoveries/stamina", drawback: "bane on some tests" },
  { id: "host-body", name: "Host Body", benefit: "boosts recoveries/stamina", drawback: "fire weakness, bane on some tests" },
  { id: "hunted", name: "Hunted", benefit: "1 skill (intrigue)", drawback: "" },
  { id: "hunter", name: "Hunter", benefit: "1 skill", drawback: "bane on some tests" },
  { id: "indebted", name: "Indebted", benefit: "", drawback: "reduced/limited wealth" },
  { id: "infernal-contract-but-like-bad", name: "Infernal Contract... But, Like, Bad", benefit: "", drawback: "bane on some tests" },
  { id: "infernal-contract", name: "Infernal Contract", benefit: "", drawback: "" },
  { id: "ivory-tower", name: "Ivory Tower", benefit: "3 skills, +language", drawback: "bane on some tests" },
  { id: "lifebonded", name: "Lifebonded", benefit: "", drawback: "" },
  { id: "lightning-soul", name: "Lightning Soul", benefit: "boosts recoveries/stamina", drawback: "damage weakness" },
  { id: "loner", name: "Loner", benefit: "skill", drawback: "" },
  { id: "lost-your-head", name: "Lost Your Head", benefit: "grants an ability", drawback: "" },
  { id: "lost-in-time", name: "Lost in Time", benefit: "", drawback: "" },
  { id: "lucky", name: "Lucky", benefit: "", drawback: "bane on some tests" },
  { id: "master-chef", name: "Master Chef", benefit: "skill (crafting)", drawback: "" },
  { id: "meddling-butler", name: "Meddling Butler", benefit: "", drawback: "" },
  { id: "medium", name: "Medium", benefit: "", drawback: "" },
  { id: "medusa-blood", name: "Medusa Blood", benefit: "grants an ability", drawback: "" },
  { id: "misunderstood", name: "Misunderstood", benefit: "", drawback: "" },
  { id: "mundane", name: "Mundane", benefit: "corruption/psychic/holy immunity", drawback: "bane on some tests" },
  { id: "outlaw", name: "Outlaw", benefit: "", drawback: "" },
  { id: "pirate", name: "Pirate", benefit: "starting treasure", drawback: "" },
  { id: "preacher", name: "Preacher", benefit: "", drawback: "" },
  { id: "primordial-sickness", name: "Primordial Sickness", benefit: "corruption/poison immunity", drawback: "fewer recoveries" },
  { id: "prisoner-of-the-synlirii", name: "Prisoner of the Synlirii", benefit: "+language", drawback: "" },
  { id: "promising-apprentice", name: "Promising Apprentice", benefit: "1 skill (crafting), an edge on tests", drawback: "bane on some tests" },
  { id: "psychic-eruption", name: "Psychic Eruption", benefit: "grants an ability", drawback: "" },
  { id: "raised-by-beasts", name: "Raised by Beasts", benefit: "skill (interpersonal), +language, an edge on tests", drawback: "" },
  { id: "refugee", name: "Refugee", benefit: "starting treasure", drawback: "" },
  { id: "rival", name: "Rival", benefit: "1 skill", drawback: "bane on some tests" },
  { id: "rogue-talent", name: "Rogue Talent", benefit: "grants an ability", drawback: "psychic weakness" },
  { id: "runaway", name: "Runaway", benefit: "1 skill (crafting)", drawback: "" },
  { id: "searching-for-a-cure", name: "Searching for a Cure", benefit: "", drawback: "" },
  { id: "secret-identity", name: "Secret Identity", benefit: "skill (intrigue)", drawback: "" },
  { id: "secret-twin", name: "Secret Twin", benefit: "starting treasure", drawback: "" },
  { id: "self-taught", name: "Self-Taught", benefit: "", drawback: "" },
  { id: "sewer-folk", name: "Sewer Folk", benefit: "", drawback: "poison weakness" },
  { id: "shadow-born", name: "Shadow Born", benefit: "", drawback: "holy weakness" },
  { id: "shared-spirit", name: "Shared Spirit", benefit: "", drawback: "" },
  { id: "shattered-legacy", name: "Shattered Legacy", benefit: "starting treasure, +language", drawback: "" },
  { id: "shipwrecked", name: "Shipwrecked", benefit: "2 skills (exploration)", drawback: "lost a language" },
  { id: "siblings-shield", name: "Sibling's Shield", benefit: "", drawback: "" },
  { id: "silent-sentinel", name: "Silent Sentinel", benefit: "1 skill (intrigue/lore), +language", drawback: "sonic weakness" },
  { id: "slight-case-of-lycanthropy", name: "Slight Case of Lycanthropy", benefit: "", drawback: "" },
  { id: "stolen-face", name: "Stolen Face", benefit: "an edge on tests", drawback: "" },
  { id: "strange-inheritance", name: "Strange Inheritance", benefit: "starting treasure", drawback: "reduced/limited wealth" },
  { id: "stripped-of-rank", name: "Stripped of Rank", benefit: "grants an ability", drawback: "" },
  { id: "thrill-seeker", name: "Thrill Seeker", benefit: "", drawback: "" },
  { id: "vampire-scion", name: "Vampire Scion", benefit: "boosts recoveries/stamina", drawback: "bane on some tests" },
  { id: "voice-in-your-head", name: "Voice in Your Head", benefit: "", drawback: "" },
  { id: "vow-of-duty", name: "Vow of Duty", benefit: "", drawback: "" },
  { id: "vow-of-honesty", name: "Vow of Honesty", benefit: "an edge on tests", drawback: "bane on some tests" },
  { id: "waking-dreams", name: "Waking Dreams", benefit: "", drawback: "" },
  { id: "war-dog-collar", name: "War Dog Collar", benefit: "grants an ability", drawback: "" },
  { id: "war-of-assassins", name: "War of Assassins", benefit: "", drawback: "" },
  { id: "ward", name: "Ward", benefit: "", drawback: "" },
  { id: "waterborn", name: "Waterborn", benefit: "grants an ability", drawback: "lightning weakness" },
  { id: "wodewalker", name: "Wodewalker", benefit: "boosts recoveries/stamina", drawback: "fire weakness" },
  { id: "wrathful-spirit", name: "Wrathful Spirit", benefit: "an edge on tests", drawback: "" },
  { id: "wrongly-imprisoned", name: "Wrongly Imprisoned", benefit: "2 skills (interpersonal)", drawback: "" },
];

export const complicationById = (id: string): DSComplication | undefined =>
  DS_COMPLICATIONS.find((c) => c.id === id);
