// lib/tools/magic-items.ts
//
// A catalog of D&D 2024 magic ITEMS: name, type, rarity, and whether it needs attunement. These four are
// facts about published items (names are not copyrightable; rarity and type are factual attributes), used
// here only as a lookup index. NO descriptive or mechanical text is included, and NO third-party price list
// is used: every price in the finder is derived by our own lib/tools/magic-item-price. Some items appear at
// more than one rarity (scaling items like Spell Scroll), and are listed once per rarity. Unofficial; not
// affiliated with or endorsed by Wizards of the Coast.

import type { Rarity } from "@/lib/tools/magic-item-price";

export type MagicItemType = "Armor" | "Potion" | "Ring" | "Rod" | "Scroll" | "Staff" | "Wand" | "Weapon" | "Wondrous Item";

export interface MagicItem {
  name: string;
  type: MagicItemType;
  rarity: Rarity;
  attunement: boolean;
}

// Single-use kinds price as consumables (about half a permanent item of the same rarity).
export const CONSUMABLE_TYPES: MagicItemType[] = ["Potion", "Scroll"];
export function isConsumableType(t: MagicItemType): boolean {
  return CONSUMABLE_TYPES.includes(t);
}

export const MAGIC_ITEMS: MagicItem[] = [
  { name: "Adventurer's Ring", type: "Ring", rarity: "common", attunement: false },
  { name: "Armor of Gleaming", type: "Armor", rarity: "common", attunement: false },
  { name: "Bead of Nourishment", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Bead of Refreshment", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Boots of False Tracks", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Candle of the Deep", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Cast-Off Armor", type: "Armor", rarity: "common", attunement: false },
  { name: "Charlatan's Die", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Cloak of Billowing", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Cloak of Many Fashions", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Clockwork Amulet", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Clothes of Mending", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Dark Shard Amulet", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Dread Helm", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Ear Horn of Hearing", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Enduring Spellbook", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Ersatz Eye", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Eternal Chalk", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Hat of Vermin", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Hat of Wizardry", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Heward's Handy Spice Pouch", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Horn of Silent Alarm", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Instrument of Illusions", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Instrument of Scribing", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Lock of Trickery", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Manifold Tool", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Mask of Changed Appearance", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Mechanical Wonder", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Moon-Touched Sword", type: "Weapon", rarity: "common", attunement: false },
  { name: "Mystery Key", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Mythallar Bracelet", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Orb of Direction", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Orb of Time", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Perfume of Bewitching", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Pipe of Smoke Monsters", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Pole of Angling", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Pole of Collapsing", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Pot of Awakening", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Potion of Climbing", type: "Potion", rarity: "common", attunement: false },
  { name: "Potion of Comprehension", type: "Potion", rarity: "common", attunement: false },
  { name: "Potion of Healing", type: "Potion", rarity: "common", attunement: false },
  { name: "Prosthetic Limb", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Rival Coin", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Rope of Mending", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Ruby of the War Mage", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Shield of Expression", type: "Armor", rarity: "common", attunement: false },
  { name: "Silvered Weapon", type: "Weapon", rarity: "common", attunement: false },
  { name: "Smoldering Armor", type: "Armor", rarity: "common", attunement: false },
  { name: "Spell Scroll", type: "Scroll", rarity: "common", attunement: false },
  { name: "Staff of Adornment", type: "Staff", rarity: "common", attunement: false },
  { name: "Staff of Birdcalls", type: "Staff", rarity: "common", attunement: false },
  { name: "Staff of Flowers", type: "Staff", rarity: "common", attunement: false },
  { name: "Sylvan Talon", type: "Weapon", rarity: "common", attunement: true },
  { name: "Talking Doll", type: "Wondrous Item", rarity: "common", attunement: true },
  { name: "Tankard of Sobriety", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Unraveling Cloak", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Veteran's Cane", type: "Wondrous Item", rarity: "common", attunement: false },
  { name: "Walloping Ammunition", type: "Weapon", rarity: "common", attunement: false },
  { name: "Wand of Conducting", type: "Wand", rarity: "common", attunement: false },
  { name: "Wand of Pyrotechnics", type: "Wand", rarity: "common", attunement: false },
  { name: "Adamantine Armor", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Adamantine Weapon", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Alarm Pylon", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Alchemy Jug", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Ammunition, +1, +2, or +3", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Amulet of Proof against Detection and Location", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Arcane Battery", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Baba Yaga's Dancing Broom", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Bag of Holding", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Bag of Tricks", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Boots of Elvenkind", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Boots of Striding and Springing", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Boots of the Winding Path", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Boots of the Winterlands", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Bracers of Archery", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Brooch of Shielding", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Broom of Flying", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Cap of Vanishing", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Cap of Water Breathing", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Circlet of Blasting", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Climber's Ammunition", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Cloak of Elvenkind", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Cloak of Protection", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Cloak of the Manta Ray", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Decanter of Endless Water", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Deck of Illusions", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Driftglobe", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Dust of Disappearance", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Dust of Dryness", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Dust of Sneezing and Choking", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Elemental Gem", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Enspelled Armor", type: "Armor", rarity: "uncommon", attunement: true },
  { name: "Enspelled Staff", type: "Staff", rarity: "uncommon", attunement: true },
  { name: "Enspelled Weapon", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Eversmoking Bottle", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Eyes of Charming", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Eyes of Minute Seeing", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Eyes of the Eagle", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Figurine of Wondrous Power", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Gauntlets of Ogre Power", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Gem of Brightness", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Gloves of Missile Snaring", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Gloves of Swimming and Climbing", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Gloves of Thievery", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Goggles of Night", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Hag Eye", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Harkon's Bite", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Harper Pin", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Hat of Disguise", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Hat of Vortexes", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Headband of Intellect", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Helm of Awareness", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Helm of Comprehending Languages", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Helm of Telepathy", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Immovable Rod", type: "Rod", rarity: "uncommon", attunement: false },
  { name: "Instrument of the Bards", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Javelin of Lightning", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Keoghtom's Ointment", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Lantern of Revealing", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Mariner's Armor", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Mechanical Wonder", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Medallion of Thoughts", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Mind Sharpener", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Mithral Armor", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Nature's Mantle", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Necklace of Adaptation", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Oil of Slipperiness", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Pearl of Power", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Periapt of Health", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Periapt of Wound Closure", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Philter of Love", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Pipes of Haunting", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Pipes Of Pestilence", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Pipes of the Sewers", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Poison Soaked Kukri", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Potion of Animal Friendship", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Fire Breath", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Giant Strength", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Growth", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Healing", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Poison", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Pugilism", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Resistance", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Potion of Water Breathing", type: "Potion", rarity: "uncommon", attunement: false },
  { name: "Quaal's Feather Token", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Quiver of Ehlonna", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Reliquary of Dawn", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Reliquary of Twilight", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Repeating Shot", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Repulsion Shield", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Returning Weapon", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Ring of Jumping", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Ring of Mind Shielding", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Ring of Swimming", type: "Ring", rarity: "uncommon", attunement: false },
  { name: "Ring of Warmth", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Ring of Water Walking", type: "Ring", rarity: "uncommon", attunement: false },
  { name: "Robe of Useful Items", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Rod of the Pact Keeper", type: "Rod", rarity: "uncommon", attunement: true },
  { name: "Rope of Climbing", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Saddle of the Cavalier", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Sending Stones", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Sentinel Shield", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Shield, +1, +2, or +3", type: "Armor", rarity: "uncommon", attunement: false },
  { name: "Silencing Satchel", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Slippers of Spider Climbing", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Spell Scroll", type: "Scroll", rarity: "uncommon", attunement: false },
  { name: "Spell-Refueling Ring", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Spiked Shield", type: "Armor", rarity: "uncommon", attunement: true },
  { name: "Staff of the Adder", type: "Staff", rarity: "uncommon", attunement: true },
  { name: "Staff of the Python", type: "Staff", rarity: "uncommon", attunement: true },
  { name: "Stone of Good Luck (Luckstone)", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Sword of Vengeance", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Sync Ring", type: "Ring", rarity: "uncommon", attunement: true },
  { name: "Thayan Spell Tattoo", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Trident of Fish Command", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Wand of Magic Detection", type: "Wand", rarity: "uncommon", attunement: false },
  { name: "Wand of Magic Missiles", type: "Wand", rarity: "uncommon", attunement: false },
  { name: "Wand of Secrets", type: "Wand", rarity: "uncommon", attunement: false },
  { name: "Wand of the War Mage, +1, +2 or +3", type: "Wand", rarity: "uncommon", attunement: true },
  { name: "Wand of Web", type: "Wand", rarity: "uncommon", attunement: true },
  { name: "Weapon, +1, +2 or +3", type: "Weapon", rarity: "uncommon", attunement: false },
  { name: "Weapon of Warning", type: "Weapon", rarity: "uncommon", attunement: true },
  { name: "Wind Fan", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Winged Boots", type: "Wondrous Item", rarity: "uncommon", attunement: true },
  { name: "Wraps of Unarmed Power", type: "Wondrous Item", rarity: "uncommon", attunement: false },
  { name: "Ammunition, +1, +2, or +3", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Amulet of Health", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Amulet of Retributive Healing", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Armor, +1, +2, or +3", type: "Armor", rarity: "rare", attunement: false },
  { name: "Armor of Resistance", type: "Armor", rarity: "rare", attunement: true },
  { name: "Armor of Vulnerability", type: "Armor", rarity: "rare", attunement: true },
  { name: "Arrow-Catching Shield", type: "Armor", rarity: "rare", attunement: true },
  { name: "Bag of Beans", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Bead of Force", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Belt of Dwarvenkind", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Belt of Giant Strength", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Berserker Axe", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Boots of Levitation", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Boots of Speed", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Bowl of Commanding Water Elementals", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Bracers of Defense", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Brazier of Commanding Fire Elementals", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Brooch of the Elements", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Cape of the Mountebank", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Censer of Controlling Air Elementals", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Chime of Opening", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Cloak of Displacement", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Cloak of the Bat", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Cube of Force", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Cube of Summoning", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Daern's Instant Fortress", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Dagger of Venom", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Dazzling Weapon", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Dimensional Shackles", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Dragon Slayer", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Elixir of Health", type: "Potion", rarity: "rare", attunement: false },
  { name: "Elven Chain", type: "Armor", rarity: "rare", attunement: false },
  { name: "Enspelled Armor", type: "Armor", rarity: "rare", attunement: true },
  { name: "Enspelled Staff", type: "Staff", rarity: "rare", attunement: true },
  { name: "Enspelled Weapon", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Figurine of Wondrous Power", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Flame Tongue", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Folding Boat", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Fork of Eddy Summoning", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Gem of Seeing", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Giant Slayer", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Glamoured Studded Leather", type: "Armor", rarity: "rare", attunement: false },
  { name: "Goggles of Foe-Finding", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Harper Pin", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Helm of Teleportation", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Heward's Handy Haversack", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Horn of Blasting", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Horn of Valhalla", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Horseshoes of Speed", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Instrument of the Bards", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Ioun Stone", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Iron Bands of Bilarro", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Mace of Disruption", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Mace of Smiting", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Mace of Terror", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Magen Handbell", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Mantle of Spell Resistance", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Mechanical Wonder", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Mythallar Cloak", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Necklace of Fireballs", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Necklace of Prayer Beads", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Oil of Etherealness", type: "Potion", rarity: "rare", attunement: false },
  { name: "Periapt of Proof against Poison", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Portable Hole", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Potion of Clairvoyance", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Diminution", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Gaseous Form", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Giant Strength", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Healing", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Heroism", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Invisibility", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Invulnerability", type: "Potion", rarity: "rare", attunement: false },
  { name: "Potion of Mind Reading", type: "Potion", rarity: "rare", attunement: false },
  { name: "Quaal's Feather Token", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Ring of Animal Influence", type: "Ring", rarity: "rare", attunement: false },
  { name: "Ring of Evasion", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of Feather Falling", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of Free Action", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of Protection", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of Resistance", type: "Ring", rarity: "rare", attunement: false },
  { name: "Ring of Spell Storing", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of the Ram", type: "Ring", rarity: "rare", attunement: true },
  { name: "Ring of X-ray Vision", type: "Ring", rarity: "rare", attunement: true },
  { name: "Robe of Eyes", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Rod of Rulership", type: "Rod", rarity: "rare", attunement: true },
  { name: "Rod of the Pact Keeper", type: "Rod", rarity: "rare", attunement: true },
  { name: "Rope of Entanglement", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Salubrious Armor", type: "Armor", rarity: "rare", attunement: true },
  { name: "Scroll of Protection", type: "Scroll", rarity: "rare", attunement: false },
  { name: "Shield, +1, +2, or +3", type: "Armor", rarity: "rare", attunement: false },
  { name: "Shield of Missile Attraction", type: "Armor", rarity: "rare", attunement: true },
  { name: "Spell Scroll", type: "Scroll", rarity: "rare", attunement: false },
  { name: "Staff of Charming", type: "Staff", rarity: "rare", attunement: true },
  { name: "Staff of Healing", type: "Staff", rarity: "rare", attunement: true },
  { name: "Staff of Swarming Insects", type: "Staff", rarity: "rare", attunement: true },
  { name: "Staff of the Woodlands", type: "Staff", rarity: "rare", attunement: true },
  { name: "Staff of Withering", type: "Staff", rarity: "rare", attunement: true },
  { name: "Stone of Controlling Earth Elementals", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Stormwalker's Cloak", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Sun Blade", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Sword of Life Stealing", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Sword of Wounding", type: "Weapon", rarity: "rare", attunement: true },
  { name: "Tentacle Rod", type: "Rod", rarity: "rare", attunement: true },
  { name: "Vicious Weapon", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Wand of Binding", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Enemy Detection", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Fear", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Fireballs", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Lightning Bolts", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Misdirection", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Paralysis", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of the War Mage, +1, +2 or +3", type: "Wand", rarity: "rare", attunement: true },
  { name: "Wand of Wonder", type: "Wand", rarity: "rare", attunement: true },
  { name: "Weapon, +1, +2 or +3", type: "Weapon", rarity: "rare", attunement: false },
  { name: "Windskiff", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Wings of Flying", type: "Wondrous Item", rarity: "rare", attunement: true },
  { name: "Wraps of Unarmed Power", type: "Wondrous Item", rarity: "rare", attunement: false },
  { name: "Ammunition, +1, +2, or +3", type: "Weapon", rarity: "very rare", attunement: false },
  { name: "Ammunition of Slaying", type: "Weapon", rarity: "very rare", attunement: false },
  { name: "Amulet of the Planes", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Animated Shield", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Armor, +1, +2, or +3", type: "Armor", rarity: "very rare", attunement: false },
  { name: "Bag of Devouring", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Belt of Giant Strength", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Candle of Invocation", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Carpet of Flying", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Cauldron of Rebirth", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Cloak of Arachnida", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Crystal Ball", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Dancing Sword", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Demon Armor", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Dragon Scale Mail", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Dwarven Plate", type: "Armor", rarity: "very rare", attunement: false },
  { name: "Dwarven Thrower", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Efreeti Bottle", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Energy Bow", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Enspelled Armor", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Enspelled Staff", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Enspelled Weapon", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Executioner's Axe", type: "Weapon", rarity: "very rare", attunement: false },
  { name: "Figurine of Wondrous Power", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Frost Brand", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Hat of Many Spells", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Helm of Brilliance", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Horn of Valhalla", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Horseshoes of a Zephyr", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Instrument of the Bards", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Ioun Stone", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Lute of Thunderous Thumping", type: "Weapon", rarity: "very rare", attunement: false },
  { name: "Manual of Bodily Health", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Manual of Gainful Exercise", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Manual of Golems", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Manual of Quickness of Action", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Mirror of Life Trapping", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Niko's Mace", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Nine Lives Stealer", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Nolzur's Marvelous Pigments", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Oathbow", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Oil of Sharpness", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Flying", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Giant Strength", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Greater Invisibility", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Healing", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Longevity", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Speed", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Potion of Vitality", type: "Potion", rarity: "very rare", attunement: false },
  { name: "Quarterstaff of the Acrobat", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Ring of Regeneration", type: "Ring", rarity: "very rare", attunement: true },
  { name: "Ring of Shooting Stars", type: "Ring", rarity: "very rare", attunement: true },
  { name: "Ring of Telekinesis", type: "Ring", rarity: "very rare", attunement: true },
  { name: "Robe of Scintillating Colors", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Robe of Stars", type: "Wondrous Item", rarity: "very rare", attunement: true },
  { name: "Rod of Absorption", type: "Rod", rarity: "very rare", attunement: true },
  { name: "Rod of Alertness", type: "Rod", rarity: "very rare", attunement: true },
  { name: "Rod of Security", type: "Rod", rarity: "very rare", attunement: false },
  { name: "Rod of the Pact Keeper", type: "Rod", rarity: "very rare", attunement: true },
  { name: "Scimitar of Speed", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Shield, +1, +2, or +3", type: "Armor", rarity: "very rare", attunement: false },
  { name: "Shield of the Cavalier", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Spell Scroll", type: "Scroll", rarity: "very rare", attunement: false },
  { name: "Spellguard Shield", type: "Armor", rarity: "very rare", attunement: true },
  { name: "Spirit Board", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Staff of Fire", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Staff of Frost", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Staff of Power", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Staff of Striking", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Staff of Thunder and Lightning", type: "Staff", rarity: "very rare", attunement: true },
  { name: "Sword of Sharpness", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Thunderous Greatclub", type: "Weapon", rarity: "very rare", attunement: true },
  { name: "Tome of Clear Thought", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Tome of Leadership and Influence", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Tome of Understanding", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Wand of Polymorph", type: "Wand", rarity: "very rare", attunement: true },
  { name: "Wand of the War Mage, +1, +2 or +3", type: "Wand", rarity: "very rare", attunement: true },
  { name: "Weapon, +1, +2 or +3", type: "Weapon", rarity: "very rare", attunement: false },
  { name: "Wraps of Unarmed Power", type: "Wondrous Item", rarity: "very rare", attunement: false },
  { name: "Apparatus of Kwalish", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Armor, +1, +2, or +3", type: "Armor", rarity: "legendary", attunement: false },
  { name: "Armor of Invulnerability", type: "Armor", rarity: "legendary", attunement: true },
  { name: "Belt of Giant Strength", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Cloak of Invisibility", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Crystal Ball of Mind Reading", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Crystal Ball of Telepathy", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Crystal Ball of True Seeing", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Cubic Gate", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Deck of Many Things", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Defender", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Efreeti Chain", type: "Armor", rarity: "legendary", attunement: true },
  { name: "Enspelled Armor", type: "Armor", rarity: "legendary", attunement: true },
  { name: "Enspelled Staff", type: "Staff", rarity: "legendary", attunement: true },
  { name: "Enspelled Weapon", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Hammer of Thunderbolts", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Holy Avenger", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Horn of Valhalla", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Instrument of the Bards", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Ioun Stone", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Iron Flask", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Luck Blade", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Moonblade", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Plate Armor of Etherealness", type: "Armor", rarity: "legendary", attunement: true },
  { name: "Potion of Giant Strength", type: "Potion", rarity: "legendary", attunement: false },
  { name: "Ring of Djinni Summoning", type: "Ring", rarity: "legendary", attunement: true },
  { name: "Ring of Elemental Command", type: "Ring", rarity: "legendary", attunement: true },
  { name: "Ring of Invisibility", type: "Ring", rarity: "legendary", attunement: true },
  { name: "Ring of Spell Turning", type: "Ring", rarity: "legendary", attunement: true },
  { name: "Ring of Three Wishes", type: "Ring", rarity: "legendary", attunement: false },
  { name: "Robe of the Archmagi", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Rod of Lordly Might", type: "Rod", rarity: "legendary", attunement: true },
  { name: "Rod of Resurrection", type: "Rod", rarity: "legendary", attunement: true },
  { name: "Scarab of Protection", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Scroll of Titan Summoning", type: "Scroll", rarity: "legendary", attunement: false },
  { name: "Sovereign Glue", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Spell Scroll", type: "Scroll", rarity: "legendary", attunement: false },
  { name: "Sphere of Annihilation", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Staff of the Magi", type: "Staff", rarity: "legendary", attunement: true },
  { name: "Sword of Answering", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Talisman of Pure Good", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Talisman of the Sphere", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Talisman of Ultimate Evil", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Tome of the Dragon", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Tome of the Stilled Tongue", type: "Wondrous Item", rarity: "legendary", attunement: true },
  { name: "Universal Solvent", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Vorpal Sword", type: "Weapon", rarity: "legendary", attunement: true },
  { name: "Well of Many Worlds", type: "Wondrous Item", rarity: "legendary", attunement: false },
  { name: "Axe of the Dwarvish Lords", type: "Weapon", rarity: "artifact", attunement: true },
  { name: "Blackrazor", type: "Weapon", rarity: "artifact", attunement: true },
  { name: "Book of Exalted Deeds", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Book of Vile Darkness", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Calimemnon Crystal", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Crown Of Horns", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Demonomicon of Iggwilv", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Ebonbane", type: "Weapon", rarity: "artifact", attunement: true },
  { name: "Eye and Hand of Vecna", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Orb of Damara", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Orb of Dragonkind", type: "Wondrous Item", rarity: "artifact", attunement: true },
  { name: "Sword of Kas", type: "Weapon", rarity: "artifact", attunement: true },
  { name: "Wand of Orcus", type: "Wand", rarity: "artifact", attunement: true },
  { name: "Wave", type: "Weapon", rarity: "artifact", attunement: true },
  { name: "Whelm", type: "Weapon", rarity: "artifact", attunement: true },
];
