-- Catalog seed: event_types + gm_event_kinds.
-- Safe to re-run: every statement carries ON CONFLICT DO NOTHING.
-- These catalogs are FK targets. If they are empty, the extractor, the coverage
-- picker, and the review queue all silently return nothing.

INSERT INTO public.event_types SELECT * FROM jsonb_populate_recordset(null::public.event_types, '[{"key": "social_opening", "label": "Social opening arose", "category": "opportunity", "default_axis": "S", "default_frame": null, "default_target": "player"}, {"key": "lore_hook", "label": "Lore / world hook dropped", "category": "opportunity", "default_axis": "E", "default_frame": null, "default_target": "fiction"}, {"key": "combat_encounter", "label": "Combat encounter began", "category": "opportunity", "default_axis": "T", "default_frame": null, "default_target": "fiction"}, {"key": "exploration_prompt", "label": "Exploration prompt arose", "category": "opportunity", "default_axis": "E", "default_frame": null, "default_target": "fiction"}, {"key": "roleplay_scene", "label": "Roleplay scene arose", "category": "opportunity", "default_axis": "N", "default_frame": null, "default_target": "fiction"}, {"key": "ic_speech", "label": "In-character speech", "category": "response", "default_axis": "N", "default_frame": "ic", "default_target": "fiction"}, {"key": "ooc_social", "label": "Out-of-character social", "category": "response", "default_axis": "S", "default_frame": "ooc", "default_target": "player"}, {"key": "tactical_call", "label": "Tactical call in combat", "category": "response", "default_axis": "T", "default_frame": "ooc", "default_target": "system"}, {"key": "rules_invocation", "label": "Rules cited / corrected", "category": "response", "default_axis": "O", "default_frame": "ooc", "default_target": "system"}, {"key": "investigation", "label": "Investigation / inquiry", "category": "response", "default_axis": "E", "default_frame": "ic", "default_target": "fiction"}, {"key": "inclusion_act", "label": "Pulled in a quiet player", "category": "response", "default_axis": "S", "default_frame": "ooc", "default_target": "player"}, {"key": "decision", "label": "Meaningful decision", "category": "response", "default_axis": null, "default_frame": "ic", "default_target": "fiction"}, {"key": "character_choice", "label": "Character-motivated choice", "category": "response", "default_axis": "N", "default_frame": "ic", "default_target": "fiction"}, {"key": "loot_grant", "label": "Loot / reward granted", "category": "reward", "default_axis": null, "default_frame": null, "default_target": "fiction"}, {"key": "milestone", "label": "Story milestone", "category": "reward", "default_axis": null, "default_frame": null, "default_target": "fiction"}, {"key": "spotlight_note", "label": "Manual spotlight note", "category": "meta", "default_axis": null, "default_frame": null, "default_target": null}]')
ON CONFLICT DO NOTHING;

INSERT INTO public.gm_event_kinds SELECT * FROM jsonb_populate_recordset(null::public.gm_event_kinds, '[{"kind": "narration", "sort": 10, "feeds": ["recap", "timeline"], "label": "Narration", "category": "narrative"}, {"kind": "scene_transition", "sort": 20, "feeds": ["recap", "timeline"], "label": "Scene transition", "category": "narrative"}, {"kind": "recap", "sort": 30, "feeds": ["recap"], "label": "GM recap", "category": "narrative"}, {"kind": "lore", "sort": 40, "feeds": ["codex", "timeline"], "label": "Lore revealed", "category": "world"}, {"kind": "location", "sort": 50, "feeds": ["codex", "timeline"], "label": "Location", "category": "world"}, {"kind": "faction", "sort": 60, "feeds": ["codex"], "label": "Faction", "category": "world"}, {"kind": "item_introduced", "sort": 70, "feeds": ["codex"], "label": "Item introduced", "category": "world"}, {"kind": "npc_introduced", "sort": 80, "feeds": ["codex", "timeline"], "label": "NPC introduced", "category": "npc"}, {"kind": "npc_voice", "sort": 90, "feeds": ["codex", "recap"], "label": "NPC dialogue", "category": "npc"}, {"kind": "npc_action", "sort": 100, "feeds": ["codex", "timeline", "recap"], "label": "NPC action", "category": "npc"}, {"kind": "npc_departed", "sort": 110, "feeds": ["codex", "timeline"], "label": "NPC departed", "category": "npc"}, {"kind": "framing", "sort": 120, "feeds": ["prep", "recap"], "label": "Decision posed", "category": "structure"}, {"kind": "hook", "sort": 130, "feeds": ["prep", "codex"], "label": "Plot hook", "category": "structure"}, {"kind": "quest_update", "sort": 140, "feeds": ["prep", "timeline", "recap"], "label": "Quest update", "category": "structure"}, {"kind": "reward", "sort": 150, "feeds": ["timeline", "recap"], "label": "Reward granted", "category": "structure"}, {"kind": "consequence", "sort": 160, "feeds": ["timeline", "recap", "prep"], "label": "Consequence", "category": "structure"}, {"kind": "ruling", "sort": 170, "feeds": ["reliability"], "label": "Rules ruling", "category": "governance"}, {"kind": "retcon", "sort": 180, "feeds": ["timeline"], "label": "Retcon", "category": "governance"}, {"kind": "meta", "sort": 190, "feeds": [], "label": "Table talk", "category": "governance"}, {"kind": "spotlight", "sort": 200, "feeds": ["prep"], "label": "Spotlight", "category": "interaction"}, {"kind": "prompt", "sort": 210, "feeds": ["prep"], "label": "Player prompt", "category": "interaction"}, {"kind": "acknowledgment", "sort": 220, "feeds": ["prep"], "label": "Player acknowledged", "category": "interaction"}]')
ON CONFLICT DO NOTHING;
